import { esc, pageSections } from './core.mjs';
import {renderInquiryForm,formStyles} from './public_form.mjs';
const colors={cyan:'#06b6ce',violet:'#7446d0',gold:'#94620a'};
export function renderPage(d,{action='',token='',utm={},preview=false,success=false,error='',step='contact',stepAction='',values={},reviewToken='',privateForm=false,mediaBase='',imageSources={}}={}) {
  const e=esc,accent=colors[d.accent] || colors.cyan,buttonText=d.accent==='cyan'?'#06232d':'#fff';
  const picture=(asset,kind)=>{
    if(!asset)return '';
    const src=imageSources[asset.id]||(mediaBase?`${mediaBase}/${asset.id}`:'');
    return src?`<img class="page-${kind}" src="${e(src)}" alt="${e(asset.alt)}" ${kind==='hero'?'fetchpriority="high"':''} decoding="async">`:'';
  };
  const renderSection=s=>{
    if(!s.visible)return '';
    if(s.kind==='main_image')return picture(d.hero_image,'hero');
    if(s.kind==='benefits')return d.benefits.length?`<section class="benefits" data-section="benefits">${d.benefits.map((b,i)=>`<div class="benefit"><span>0${i+1}</span>${e(b)}</div>`).join('')}</section>`:'';
    if(s.kind==='faq')return d.faq.length?`<section class="faq" data-section="faq"><h2>Questions, answered.</h2>${d.faq.map(f=>`<details><summary>${e(f.q)}</summary><p>${e(f.a)}</p></details>`).join('')}</section>`:'';
    if(s.kind==='text')return `<section class="text-section" data-section="${e(s.id)}"><h2>${e(s.heading)}</h2><p>${e(s.body)}</p></section>`;
    return `<section id="contact" class="formbox" data-section="inquiry">${success?`<div class="success"><h2>Thank you.</h2><p>${e(d.thank_you)}</p>${d.booking_url?`<a class="btn" href="${e(d.booking_url)}" rel="noopener noreferrer">Continue →</a>`:''}</div>`:renderInquiryForm(d,{action,stepAction,token,utm,preview,step,values,reviewToken,error})}</section>`;
  };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(d.headline)} | ${e(d.brand)}</title><meta name="description" content="${e(d.subheadline)}"><meta name="robots" content="${preview||privateForm?'noindex,nofollow':'index,follow'}"><style>
*{box-sizing:border-box}body{overflow-wrap:anywhere}html{scroll-behavior:smooth}body{margin:0;background:#f7f9fc;color:#10203b;font:17px/1.6 system-ui,sans-serif}a{color:inherit}header,main,footer{max-width:1120px;margin:auto;padding:26px}header{display:flex;justify-content:space-between;gap:20px;align-items:center}header b{font-size:22px;letter-spacing:1px}nav a{font-size:14px}section{margin:28px 0}.hero{background:#091c33;border-radius:28px;color:#fff;padding:70px 54px;position:relative;overflow:hidden}.hero:after{content:'';position:absolute;width:300px;height:300px;border:40px solid ${accent};border-radius:50%;opacity:.12;right:-60px;bottom:-120px;pointer-events:none}.hero small{letter-spacing:2px;color:#b7ccdf;text-transform:uppercase}.hero h1{font-size:clamp(32px,5vw,62px);line-height:1.1;max-width:810px;margin:20px 0}.hero p{color:#c9d8e6;max-width:730px;white-space:pre-line}.btn,button{display:inline-block;border:0;border-radius:12px;background:${accent};color:${buttonText};padding:16px 24px;font:700 16px system-ui;cursor:pointer;text-decoration:none}.benefits{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.benefit,.formbox,.faq{background:#fff;border:1px solid #dbe3ef;border-radius:20px;padding:24px}.benefit span{display:block;color:${accent};font-weight:800;margin-bottom:8px}.formbox{max-width:780px;margin:40px auto}.formbox h2{font-size:30px;line-height:1.25}label{display:block;margin-top:16px;font-weight:600}input,textarea{display:block;width:100%;border:1px solid #b8c7d9;border-radius:10px;padding:13px;font:inherit;margin-top:7px;background:#fff;color:#10203b}textarea{min-height:110px}input[type=checkbox]{display:inline-block;width:auto;margin-right:10px}.consent{font-size:14px;font-weight:400}.formbox button{margin-top:20px}.trap{position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden}.faq details{padding:16px 0;border-bottom:1px solid #e2e9f0}.faq summary{cursor:pointer;font-weight:650}.faq p{white-space:pre-line}.note{font-size:13px;color:#53667c}.error{color:#aa1732;border:1px solid #e5b8c1;padding:16px;border-radius:12px}.success{padding:38px;background:#e6faf3;border-radius:20px}footer{font-size:13px;color:#53667c;display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap}.preview{background:#fef3c7;padding:12px;text-align:center;font-size:14px}.layout-event .hero{border-top:8px solid ${accent}}.layout-product .benefit{border-top:4px solid ${accent}}@media(max-width:600px){header,main,footer{padding:18px}.hero{padding:36px 24px}.formbox{padding:22px}.hero h1{font-size:38px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
.brand{display:flex;align-items:center;gap:14px;min-width:0}.brand b{overflow-wrap:anywhere}.page-logo{width:64px;height:64px;object-fit:contain;flex-shrink:0}.page-hero{display:block;width:100%;max-height:560px;object-fit:contain;background:#e7edf4;border-radius:22px;margin-top:24px}@media(max-width:600px){.page-logo{width:48px;height:48px}.brand{gap:10px}header b{font-size:18px}}
.text-section{padding:32px;background:#fff;border:1px solid #dbe3ef;border-radius:20px}.text-section h2{font-size:28px;line-height:1.25;margin-top:0}.text-section p{white-space:pre-line;margin-bottom:0}@media(max-width:600px){.text-section{padding:22px}.text-section h2{font-size:24px}}
${formStyles}
</style></head><body class="layout-${e(d.layout)}">${preview?'<div class="preview">Draft preview · Submissions are disabled</div>':''}<header><div class="brand">${picture(d.logo,'logo')}<b>${e(d.brand)}</b></div><nav><a href="#contact">${e(d.cta)}</a></nav></header><main><section class="hero"><small>${e(d.brand)}</small><h1>${e(d.headline)}</h1><p>${e(d.subheadline)}</p><a class="btn" href="#contact">${e(d.cta)} →</a></section>
${pageSections(d.sections).map(section=>renderSection(section)).join('')}</main><footer><span>© ${new Date().getUTCFullYear()} ${e(d.brand)}</span><span>${d.contact_email?e(d.contact_email)+' · ':''}Powered by KORLIX</span></footer></body></html>`;
}
export const publicHeaders={
  'Cache-Control':'no-store', 'X-Content-Type-Options':'nosniff', 'Referrer-Policy':'strict-origin-when-cross-origin',
  'Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",
  'Permissions-Policy':'camera=(), microphone=(), geolocation=()',
};
