import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import express from 'express';
import {plan,generateStep,WorkflowError} from '../agent_studio/model.mjs';
import {registerAgentStudio} from '../agent_studio/routes.mjs';

const owner=randomUUID(),other=randomUUID(),usage=randomUUID();
let db,server,base,runtime,waiter,generateFails=false,contextCalls=[],generations=0;
const recipe=()=>({id:randomUUID(),title:'Launch brief',objective:'Plan a launch with known facts.',priority:'high',use_memory:false,steps:[
 {agent_id:'general',title:'Plan',instruction:'Write a plan.'},{agent_id:'doc_wizard',title:'Draft',instruction:'Use the approved plan.'}]});
const rpc=async(actor,action,id=null,data={})=>(await db.query('select public.korlix_agent_workflow_v1($1,$2,$3,$4::jsonb) result',[actor,action,id,JSON.stringify(data)])).rows[0].result;
const adapter={rpc:async(_name,p)=>{try{return {data:await rpc(p.p_actor,p.p_action,p.p_id,p.p_data)};}catch(e){return {error:{code:e.code,message:e.message}};}}};
const access={allowed:true,usageId:usage,creditLimit:100,requestLimit:100};
async function api(path='',body,method='GET',actor=owner,status=200){const res=await fetch(base+path,{method,headers:{Authorization:actor,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await res.json();assert.equal(res.status,status,JSON.stringify(data));assert.equal(res.headers.get('cache-control'),'no-store');return data;}
async function create(){return (await api('',recipe(),'POST',owner,201)).workflow;}
async function start(w,key=randomUUID()){return rpc(owner,'start',w.id,{attempt_id:key,revision:w.revision,usage_id:usage,credit_limit:100,request_limit:100,agent_version:7});}
async function finish(w,output='A concrete plan.'){return rpc(owner,'finish',w.id,{attempt_id:w.attempt_id,output});}
async function act(w,action,data={}){return rpc(owner,action,w.id,{revision:w.revision,...data});}
async function credits(){return (await db.query('select credits_used from usage_counters where id=$1',[usage])).rows[0].credits_used;}
before(async()=>{
 db=new PGlite();await db.exec(`create schema auth;create role anon;create role authenticated;create role service_role bypassrls;create table auth.users(id uuid primary key);
 create table public.usage_counters(id uuid primary key,user_id uuid,credits_used integer default 0,standard_generations integer default 0,live_search_generations integer default 0,pdf_generations integer default 0,updated_at timestamptz);`);
 await db.query('insert into auth.users values($1),($2)',[owner,other]);await db.query('insert into usage_counters(id,user_id)values($1,$2)',[usage,owner]);
 const migrations=new URL('../../supabase/migrations/',import.meta.url);
 const file=(await readdir(migrations)).find(n=>n.endsWith('_agent_studio_workflows.sql'));
 await db.exec(await readFile(new URL(file,migrations),'utf8'));
 const app=express();app.use(express.json());runtime=registerAgentStudio(app,{database:adapter,requireUser:async q=>{if(![owner,other].includes(q.headers.authorization))throw Error();return {id:q.headers.authorization};},
  loadContext:async(u,id,useMemory)=>{contextCalls.push({owner:u.id,id,useMemory});if(id==='missing')throw new WorkflowError('Agent not found.',404);return {version:7,instructions:'Private approved agent context'};},
  aiAccess:async()=>access,generate:async()=>{generations++;if(waiter)await waiter;if(generateFails)throw Error('provider details must not leak');return 'A concrete written deliverable.';},logger:{warn(){}}});
 server=app.listen(0);await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api/agent-studio/workflows`;
});
beforeEach(async()=>{assert.equal(runtime.active.size,0);await db.exec('truncate korlix_agent_workflow_attempts,korlix_agent_workflows;update usage_counters set credits_used=0,standard_generations=0;');waiter=null;generateFails=false;contextCalls=[];generations=0;});
after(async()=>{await new Promise(r=>server.close(r));await db.close();});

test('routes require authentication and suppress caching',async()=>{await api('',undefined,'GET','',401);await api('',recipe(),'POST','',401);});
test('workflow plans bound inputs and strip client-provided execution state',()=>{const b=recipe();b.steps[0].status='approved';b.steps[0].output='spoof';const v=plan(b);assert.equal(v.steps[0].status,'pending');assert.equal(v.steps[0].output,undefined);assert.throws(()=>plan({...b,steps:[]}));assert.throws(()=>plan({...b,steps:Array(9).fill(b.steps[0])}));assert.throws(()=>plan({...b,use_memory:'true'}));assert.throws(()=>plan({...b,title:'x'.repeat(121)}));});
test('create validates agent access and stores private workflow',async()=>{const w=await create();assert.equal(w.state,'ready');assert.equal(w.owner_id,undefined);assert.equal((await api()).workflows.length,1);assert.equal((await api('',undefined,'GET',other)).workflows.length,0);await api('/'+w.id,undefined,'GET',other,404);await api('/'+w.id+'/actions',{action:'cancel',revision:1,confirmed:true},'POST',other,404);assert.equal(contextCalls.length,2);});
test('unavailable agents cannot be assigned',async()=>{const b=recipe();b.steps[0].agent_id='missing';await api('',b,'POST',owner,404);assert.equal((await api()).workflows.length,0);});
test('creation is idempotent for the same request id',async()=>{const b=recipe();const a=await api('',b,'POST',owner,201);const c=await api('',b,'POST',owner,201);assert.equal(a.workflow.id,c.workflow.id);assert.equal((await api()).workflows.length,1);});
test('each step must finish and receive review before the next handoff',async()=>{let w=await create();await assert.rejects(act(w,'approve'),/reviewed/);w=await start(w);assert.equal(w.state,'running');assert.equal(await credits(),1);await assert.rejects(start(w),/Review/);w=await finish(w);assert.equal(w.steps[0].status,'review');assert.equal(w.steps[0].agent_version,7);await assert.rejects(start(w),/Review/);w=await act(w,'approve');assert.equal(w.cursor,1);assert.equal(w.state,'ready');w=await finish(await start(w));w=await act(w,'approve');assert.equal(w.state,'completed');assert.equal(w.cursor,2);assert.equal(await credits(),2);});
test('replayed run key does not charge or execute twice, including after review',async()=>{const w=await create(),key=randomUUID();let running=await start(w,key);assert.equal((await start(w,key)).replayed,true);await finish(running);assert.equal((await start(w,key)).replayed,true);assert.equal(await credits(),1);});
test('stale edits fail instead of overwriting another device',async()=>{const w=await create();await act(w,'pause');await assert.rejects(act(w,'cancel'),/changed/);assert.equal((await rpc(owner,'get',w.id)).state,'paused');});
test('pause and resume preserve review state and output',async()=>{let w=await finish(await start(await create()));w=await act(w,'pause');assert.equal(w.state,'paused');await assert.rejects(start(w),/resume/);w=await act(w,'resume');assert.equal(w.state,'review');assert.equal(w.steps[0].output,'A concrete plan.');});
test('feedback reruns the same step while keeping earlier approved steps',async()=>{let w=await act(await finish(await start(await create())),'approve');w=await finish(await start(w));w=await act(w,'revise',{feedback:'Make the draft concise.'});assert.equal(w.cursor,1);assert.equal(w.steps[0].status,'approved');assert.equal(w.steps[1].feedback,'Make the draft concise.');w=await finish(await start(w),'A concise final draft.');assert.equal(w.steps[1].output,'A concise final draft.');assert.equal(await credits(),3);});
test('failure refunds once and late completion cannot resurrect it',async()=>{let w=await start(await create());const original=w;w=await rpc(owner,'fail',w.id,{attempt_id:w.attempt_id});assert.equal(w.state,'failed');assert.equal(await credits(),0);await rpc(owner,'fail',w.id,{attempt_id:w.attempt_id});assert.equal(await credits(),0);assert.equal((await finish(original)).state,'failed');let newer=await start(w);await finish(original);assert.equal((await rpc(owner,'get',w.id)).attempt_id,newer.attempt_id);await finish(newer);assert.equal(await credits(),1);});
test('cancel invalidates running output and refunds its credit',async()=>{let w=await start(await create());const original=w;w=await act(w,'cancel');assert.equal(w.state,'cancelled');assert.equal(await credits(),0);await finish(original);assert.equal((await rpc(owner,'get',w.id)).state,'cancelled');assert.equal((await act(w,'delete')).deleted,true);});
test('orphaned work recovers to failed with a single refund',async()=>{let w=await start(await create());await db.query("update korlix_agent_workflow_attempts set started_at=now()-interval '6 minutes' where id=$1",[w.attempt_id]);await rpc(owner,'recover');w=await rpc(owner,'get',w.id);assert.equal(w.state,'failed');assert.equal(await credits(),0);await rpc(owner,'recover');assert.equal(await credits(),0);});
test('one active step per user across workflows',async()=>{const a=await create(),b=await create();await start(a);await assert.rejects(start(b),/still running/);assert.equal(await credits(),1);});
test('credit denial atomically leaves step ready and uncharged',async()=>{const w=await create();await assert.rejects(rpc(owner,'start',w.id,{attempt_id:randomUUID(),revision:1,usage_id:usage,credit_limit:0,request_limit:100,agent_version:7}),/allowance/);assert.equal((await rpc(owner,'get',w.id)).state,'ready');assert.equal(await credits(),0);});
test('approval and destructive API actions require explicit confirmation',async()=>{const w=await create();await api('/'+w.id+'/actions',{revision:1,action:'cancel'},'POST',owner,400);await api('/'+w.id+'/actions',{revision:1,action:'finish',confirmed:true},'POST',owner,400);});
test('public roles cannot access tables or invoke privileged RPC',async()=>{const r=await db.query("select has_table_privilege('authenticated','korlix_agent_workflows','select') table_access,has_function_privilege('anon','korlix_agent_workflow_v1(uuid,text,uuid,jsonb)','execute') rpc_access,(select relrowsecurity from pg_class where oid='korlix_agent_workflows'::regclass) rls");assert.deepEqual(r.rows[0],{table_access:false,rpc_access:false,rls:true});});
test('HTTP run is durable, polls, charges once and passes memory choice to the right agent',async()=>{let done;waiter=new Promise(r=>done=r);const w=await create(),key=randomUUID(),body={revision:w.revision,attempt_id:key};let r=await api('/'+w.id+'/run',body,'POST',owner,202);assert.equal(r.workflow.state,'running');await api('/'+w.id+'/run',body,'POST');assert.equal(generations,1);assert.equal(contextCalls.at(-1).useMemory,false);done();for(let i=0;i<60&&runtime.active.size;i++)await new Promise(r=>setTimeout(r,5));r=await api('/'+w.id);assert.equal(r.workflow.state,'review');assert.equal(await credits(),1);});
test('provider failure becomes retryable without leaking provider details',async()=>{generateFails=true;const w=await create();await api('/'+w.id+'/run',{revision:w.revision,attempt_id:randomUUID()},'POST',owner,202);for(let i=0;i<60&&runtime.active.size;i++)await new Promise(r=>setTimeout(r,5));const r=await api('/'+w.id);assert.equal(r.workflow.state,'failed');assert.equal(await credits(),0);assert(!JSON.stringify(r).includes('provider details'));});
test('generation uses approved handoffs, no external tools, and configured model',async()=>{const w=recipe();w.cursor=1;w.steps[0]={...w.steps[0],status:'approved',output:'Approved facts'};let request,options;const result=await generateStep({client:{responses:{create:async(q,o)=>{request=q;options=o;return {status:'completed',output_text:'Useful result'};}}},workflow:w,context:{instructions:'approved context'}});assert.equal(result,'Useful result');assert.equal(request.tools,undefined);assert.equal(request.store,false);assert.equal(request.model,'gpt-6-astra');assert.equal(options.maxRetries,0);assert(request.instructions.includes('K-Nova'));const input=JSON.parse(request.input[0].content[0].text);assert.equal(input.approved_handoffs[0].approved_output,'Approved facts');});
