import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import express from 'express';
import sharp from 'sharp';
import {registerAppPortals,paymentUrl,portalFile} from '../app_studio/portal.mjs';
import {template} from '../app_studio/model.mjs';
let db,server,base,service,owner,customer,other,staff,unverified,banned,objects;const actors=new Map();
const hash=v=>createHash('sha256').update(v).digest('hex');
const rpc=async(actor,action,id=null,data={})=>(await db.query('select public.korlix_app_portal_v1($1,$2,$3,$4) r',[actor,action,id,data])).rows[0].r;
const database={rpc:async(_,p)=>{try{return {data:await rpc(p.p_actor,p.p_action,p.p_id,p.p_data)};}catch(error){if(process.env.APP_DEBUG)console.error(error.message,error.where);return {error};}},storage:{from(bucket){assert.equal(bucket,'korlix-app-portals');return {upload:async(path,bytes)=>{objects.set(path,Buffer.from(bytes));return {data:{path}};},download:async path=>({data:objects.has(path)?new Blob([objects.get(path)]):null,error:objects.has(path)?null:Error('Missing')}),remove:async paths=>{for(const p of paths)objects.delete(p);return {};}};}}};
async function user(n,{verified=true,ban=false}={}){const id=randomUUID(),session=randomUUID(),email=n+'.'+id.slice(0,7)+'@example.test',token='fixture.'+Buffer.from(JSON.stringify({session_id:session})).toString('base64url')+'.fixture';await db.query("insert into auth.users(id,email,email_confirmed_at,banned_until)values($1,$2,case when $3 then now() else null end,case when $4 then now()+interval '1 day' else null end)",[id,email,verified,ban]);await db.query('insert into auth.sessions(id,user_id)values($1,$2)',[session,id]);const u={id,email,session,token};actors.set(token,u);return u;}
async function api(path='',{actor=owner,method='GET',body,status=200,runtimeToken,raw=false}={}){const headers={};if(runtimeToken)headers.Authorization='Portal '+runtimeToken;else if(actor)headers.Authorization='Bearer '+actor.token;if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(base+path,{method,headers,...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});assert.equal(r.status,status,await (async()=>r.status===status?'':r.clone().text())());if(raw)return r;const d=await r.json();return d;}
async function project(){const id=randomUUID();await db.query("select public.korlix_app_studio_v1($1,'create',$2,$3)",[owner.id,id,{name:'Fixture Portal',brief:{idea:'Customer portal'},spec:template('crm')}]);return id;}
async function publish(id,extra={},status=200){return api('/projects/'+id+'/portal',{method:'PUT',body:{version:0,project_version:1,name:'Fixture business',description:'Private customer support',payment_url:'',published:true,confirmed:true,...extra},status});}
async function invite(id,u=customer,role='customer'){return api('/portals/'+id+'/invites',{method:'POST',body:{email:u.email,role,expires_days:7},status:201});}
async function join(id,u=customer,role='customer'){const i=await invite(id,u,role);return api('/portals/join',{actor:u,method:'POST',body:{code:i.code,portal_id:id}});}
async function launch(id,u=owner){const d=await api('/portals/'+id+'/session',{actor:u,method:'POST'});assert.match(d.launch_url,new RegExp('/portals/'+id+'/#launch='));return new URL(d.launch_url).hash.slice(8);}
async function session(id,u=owner){const code=await launch(id,u);return (await api('/portals/'+id+'/runtime/exchange',{actor:null,method:'POST',body:{code}})).token;}
async function request(id,token,extra={}){return (await api('/portals/'+id+'/runtime/requests',{runtimeToken:token,method:'POST',body:{request_key:randomUUID(),title:'Replace a fixture',description:'Please review the attached photo.',...extra},status:201})).request;}
const runpath=(id,p='')=>'/portals/'+id+'/runtime'+p;
test.before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create role supabase_auth_admin;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,banned_until timestamptz);create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id) on delete cascade,not_after timestamptz);create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key,bucket_id text,name text);alter table storage.objects enable row level security;grant select,insert on storage.objects to anon,authenticated;grant usage on schema storage to anon,authenticated;create policy legacy_wide on storage.objects for all to anon,authenticated using(true) with check(true);create table public.usage_counters(id uuid primary key,user_id uuid,credits_used integer default 0,standard_generations integer default 0,live_search_generations integer default 0,pdf_generations integer default 0,updated_at timestamptz default now());grant all on usage_counters to service_role;grant usage on schema auth to supabase_auth_admin;grant select,delete on auth.users to supabase_auth_admin;`);const dir=new URL('../../supabase/migrations/',import.meta.url),names=await readdir(dir);for(const suffix of ['_app_studio_projects.sql','_app_studio_customer_portals.sql'])await db.exec(await readFile(new URL(names.find(n=>n.endsWith(suffix)),dir),'utf8'));const app=express();app.use(express.json());service=registerAppPortals(app,{database,requireUser:async q=>actors.get(q.headers.authorization?.slice(7)),autoStart:false,logger:{warn(){}}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port+'/api/app-studio';});
test.beforeEach(async()=>{await db.exec('reset role');objects=new Map();owner=await user('owner');customer=await user('customer');other=await user('other');staff=await user('staff');unverified=await user('pending',{verified:false});banned=await user('banned',{ban:true});await db.exec('set role service_role');});
test.after(async()=>{service?.stop();server?.closeAllConnections();if(server)await new Promise(r=>server.close(r));await db?.close();});
test('private management requires verified Korlix authentication and exposes honest capabilities',async()=>{await api('/portals',{actor:null,status:401});await api('/portals',{actor:unverified,status:403});await api('/portals',{actor:banned,status:403});const d=await api('/portals');assert.equal(d.capabilities.payments,'external_link');assert.deepEqual(d.portals,[]);});
test('publication freezes project version, strips sample data, and rejects stale or foreign changes',async()=>{const id=await project();assert.equal((await api('/projects/'+id+'/portal')).portal,null);let d=await publish(id);assert.equal(d.portal.version,1);assert.equal(d.portal.role,'owner');assert(!JSON.stringify(d).includes('jordan@example.com'));await api('/projects/'+id+'/portal',{actor:other,status:404});await publish(id,{version:0},409);await api('/projects/'+id+'/portal',{method:'PUT',body:{version:1,project_version:2,name:'Stale',description:'',published:true,payment_url:'',confirmed:true},status:409});assert.equal((await api('/portals')).portals.length,1);});
test('invitation binds verified email, one use, expected portal, and conceals token hashes',async()=>{const id=await project();await publish(id);const i=await invite(id);assert.equal(i.code.length,43);assert.match(i.join_url,/#invite=/);assert(!i.join_url.includes('&invite='));assert.equal(i.invite.code_hash,undefined);await api('/portals/join',{actor:other,method:'POST',body:{code:i.code},status:404});await api('/portals/join',{actor:customer,method:'POST',body:{code:i.code,portal_id:randomUUID()},status:404});const d=await api('/portals/join',{actor:customer,method:'POST',body:{code:i.code,portal_id:id}});assert.equal(d.portal.role,'customer');await api('/portals/join',{actor:customer,method:'POST',body:{code:i.code},status:404});assert.equal((await api('/portals',{actor:customer})).portals[0].role,'customer');const m=await api('/projects/'+id+'/portal');assert.equal(m.members[0].email,customer.email);assert(!JSON.stringify(m).includes(hash(i.code)));});
test('staff invitations require owner and revocation prevents redemption',async()=>{const id=await project();await publish(id);await join(id,staff,'staff');await api('/portals/'+id+'/invites',{actor:staff,method:'POST',body:{email:other.email,role:'staff'},status:403});const i=await invite(id,other);await api('/portals/'+id+'/invites/'+i.invite.id,{method:'DELETE',body:{confirmed:true}});await api('/portals/join',{actor:other,method:'POST',body:{code:i.code},status:404});});
test('launch codes are single-use, portal scoped, expire, and never transfer Supabase tokens',async()=>{const id=await project();await publish(id);const code=await launch(id);const d=await api(runpath(id,'/exchange'),{actor:null,method:'POST',body:{code}});assert.equal(d.token.length,43);assert(!d.token.includes(owner.token));await api(runpath(id,'/exchange'),{actor:null,method:'POST',body:{code},status:403});await api(runpath(randomUUID()),{runtimeToken:d.token,status:403});const next=await launch(id);await db.query("update korlix_app_portal_sessions set expires_at=now()-interval '1 second' where token_hash=$1",[hash(next)]);await api(runpath(id,'/exchange'),{actor:null,method:'POST',body:{code:next},status:403});});
test('global Korlix logout, account ban, session expiry and portal logout stop access immediately',async()=>{const id=await project();await publish(id);let token=await session(id);await api(runpath(id),{runtimeToken:token});await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[owner.session]);await db.exec('set role service_role');await api(runpath(id),{runtimeToken:token,status:403});await db.exec('reset role');await db.query('insert into auth.sessions(id,user_id)values($1,$2)',[owner.session,owner.id]);await db.exec('set role service_role');token=await session(id);await db.exec('reset role');await db.query("update auth.users set banned_until=now()+interval '1 day' where id=$1",[owner.id]);await db.exec('set role service_role');await api(runpath(id),{runtimeToken:token,status:403});await db.exec('reset role');await db.query('update auth.users set banned_until=null where id=$1',[owner.id]);await db.exec('set role service_role');await api(runpath(id,'/logout'),{runtimeToken:token,method:'POST'});await api(runpath(id),{runtimeToken:token,status:403});token=await session(id);await db.query("update korlix_app_portal_sessions set expires_at=now()-interval '1 second' where token_hash=$1",[hash(token)]);await api(runpath(id),{runtimeToken:token,status:403});});
test('customers see only their own cloud requests, staff see all, and repeated submit creates one',async()=>{const id=await project();await publish(id);await join(id);await join(id,other);await join(id,staff,'staff');const c=await session(id,customer),o=await session(id,other),s=await session(id,staff),key=randomUUID();const r=await request(id,c,{request_key:key});const again=await request(id,c,{request_key:key});assert.equal(again.id,r.id);await request(id,o,{title:'Other private details'});assert.equal((await api(runpath(id),{runtimeToken:c})).requests.length,1);assert.equal((await api(runpath(id),{runtimeToken:s})).requests.length,2);await api(runpath(id,'/requests/'+r.id),{runtimeToken:o,status:404});await api(runpath(id,'/requests/'+r.id+'/status'),{runtimeToken:c,method:'PUT',body:{version:1,status:'completed'},status:403});const changed=await api(runpath(id,'/requests/'+r.id+'/status'),{runtimeToken:s,method:'PUT',body:{version:1,status:'in_progress'}});assert.equal(changed.request.version,2);await api(runpath(id,'/requests/'+r.id+'/status'),{runtimeToken:s,method:'PUT',body:{version:1,status:'completed'},status:409});});
test('conversation is shared only within a request and duplicate reply is idempotent',async()=>{const id=await project();await publish(id);await join(id);await join(id,other);const c=await session(id,customer),o=await session(id,other),s=await session(id),r=await request(id,c),message={request_key:randomUUID(),body:'<script>alert(1)</script> literal text'};for(let j=0;j<2;j++)await api(runpath(id,'/requests/'+r.id+'/messages'),{runtimeToken:c,method:'POST',body:message,status:201});const d=await api(runpath(id,'/requests/'+r.id),{runtimeToken:s});assert.equal(d.messages.length,1);assert.equal(d.messages[0].body,message.body);await api(runpath(id,'/requests/'+r.id+'/messages'),{runtimeToken:o,method:'POST',body:{...message,request_key:randomUUID()},status:404});});
test('membership removal revokes runtime and unused replacement invitations',async()=>{const id=await project();await publish(id);await join(id);const token=await session(id,customer),i=await invite(id);await api('/portals/'+id+'/members/'+customer.id,{method:'DELETE',body:{confirmed:true}});await api(runpath(id),{runtimeToken:token,status:403});await api('/portals/join',{actor:customer,method:'POST',body:{code:i.code},status:404});await api('/portals/'+id,{actor:customer,status:404});});
test('unpublish revokes runtime and preserves records for later republish',async()=>{const id=await project();await publish(id);const token=await session(id),r=await request(id,token);await publish(id,{version:1,published:false});await api(runpath(id),{runtimeToken:token,status:403});await api('/portals/'+id+'/session',{method:'POST',status:404});await publish(id,{version:2,published:true,name:'Updated brand'});const next=await session(id);const d=await api(runpath(id),{runtimeToken:next});assert.equal(d.portal.name,'Updated brand');assert.equal(d.requests[0].id,r.id);});
test('private uploads strip image metadata, enforce ownership, verify integrity, and delete durably',async()=>{const id=await project();await publish(id);await join(id);await join(id,other);const c=await session(id,customer),o=await session(id,other),s=await session(id),r=await request(id,c);const image=await sharp({create:{width:10,height:10,channels:3,background:'#ff0000'}}).jpeg().withMetadata().toBuffer();const form=new FormData();form.append('file',new Blob([image],{type:'image/jpeg'}),'site.jpg');const d=await api(runpath(id,'/requests/'+r.id+'/files'),{runtimeToken:c,method:'POST',body:form,status:201});assert.equal(d.files.length,1);assert.equal(d.files[0].path,undefined);const f=d.files[0],response=await api(runpath(id,'/files/'+f.id),{runtimeToken:c,raw:true});assert.equal(response.headers.get('content-type'),'application/octet-stream');const bytes=Buffer.from(await response.arrayBuffer());assert.equal((await sharp(bytes).metadata()).exif,undefined);await api(runpath(id,'/files/'+f.id),{runtimeToken:o,status:404});const path=[...objects.keys()][0];objects.set(path,Buffer.from('corrupted'));await api(runpath(id,'/files/'+f.id),{runtimeToken:s,status:503});await api(runpath(id,'/files/'+f.id),{runtimeToken:c,method:'DELETE',body:{confirmed:true}});await db.query("update korlix_app_portal_gc set created_at=now()-interval '3 minutes'");await service.cleanup();assert.equal(objects.size,0);await api(runpath(id,'/files/'+f.id),{runtimeToken:c,status:404});});
test('request deletion queues all private attachments and leaves no cloud records',async()=>{const id=await project();await publish(id);const s=await session(id),r=await request(id,s);const form=new FormData();form.append('file',new Blob([Buffer.from('%PDF-1.4\nfixture\n%%EOF')],{type:'application/pdf'}),'quote.pdf');await api(runpath(id,'/requests/'+r.id+'/files'),{runtimeToken:s,method:'POST',body:form,status:201});await api(runpath(id,'/requests/'+r.id),{runtimeToken:s,method:'DELETE',body:{version:1,confirmed:true}});await db.query("update korlix_app_portal_gc set created_at=now()-interval '3 minutes'");await service.cleanup();assert.equal(objects.size,0);assert.equal((await api(runpath(id),{runtimeToken:s})).requests.length,0);});
test('account deletion as auth admin cascades files into durable GC without extra auth-admin grants',async()=>{const id=await project();await publish(id);const s=await session(id),r=await request(id,s);const form=new FormData();form.append('file',new Blob([Buffer.from('%PDF-1.4\nfixture\n%%EOF')]),'quote.pdf');await api(runpath(id,'/requests/'+r.id+'/files'),{runtimeToken:s,method:'POST',body:form,status:201});await db.exec('set role supabase_auth_admin');await db.query('delete from auth.users where id=$1',[owner.id]);await db.exec('set role service_role');assert.equal((await db.query('select count(*) n from korlix_app_portal_gc')).rows[0].n,1);await db.query("update korlix_app_portal_gc set created_at=now()-interval '3 minutes'");await service.cleanup();assert.equal(objects.size,0);await api(runpath(id),{runtimeToken:s,status:403});});
test('anonymous/authenticated roles cannot read portal tables, run RPC, or use legacy storage policies',async()=>{for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(db.query('select * from korlix_app_portals'),/permission denied/);await assert.rejects(db.query("select korlix_app_portal_v1(null,'list')"),/permission denied/);await assert.rejects(db.query("insert into storage.objects(id,bucket_id,name)values($1,'korlix-app-portals','x')",[randomUUID()]),/row-level security/);await assert.rejects(db.query('select email from auth.users'),/permission denied/);}await db.exec('set role service_role');});
test('payment links are public HTTPS, no embedded credentials or local endpoints',()=>{assert.equal(paymentUrl('https://pay.example.com/customer#private'),'https://pay.example.com/customer');assert.equal(paymentUrl(''),'');for(const url of ['javascript:alert(1)','http://example.com','https://user:pass@example.com','https://127.0.0.1/x','https://localhost/x','https://[::1]/','https://example.local/x','https://example.com:444/x'])assert.throws(()=>paymentUrl(url));});
test('file validation rejects executable HTML, invalid PDF and oversize inputs',async()=>{for(const buffer of [Buffer.from('<script>alert(1)</script>'),Buffer.from('%PDF-1.4 incomplete'),Buffer.alloc(5242881)])await assert.rejects(portalFile({buffer,originalname:'document.pdf'}));});
test('cleanup retains queued paths after storage failure and acknowledges only a successful retry',async()=>{
 const pending=['fixture/retired-file'];let failRemove=true,acknowledged=0;
 const cleanupDatabase={rpc:async(_name,p)=>p.p_action==='cleanup'?{data:[...pending]}:(acknowledged++,pending.splice(0),{data:{}})};
 const cleanupStorage={storage:{from:()=>({remove:async paths=>{assert.deepEqual(paths,pending);return failRemove?{error:Error('offline')}:{data:[]};}})}};
 const isolated=registerAppPortals(express(),{database:cleanupDatabase,storageDatabase:cleanupStorage,requireUser:async()=>null,autoStart:false,logger:{warn(){}}});
 await isolated.cleanup();assert.equal(acknowledged,0);assert.equal(pending.length,1);
 failRemove=false;await isolated.cleanup();assert.equal(acknowledged,1);assert.equal(pending.length,0);isolated.stop();
});
test('unfinished uploads survive the active window and are reclaimed after the cleanup grace period',async()=>{
 const id=await project();await publish(id);const token=await session(id),r=await request(id,token),fileId=randomUUID();
 const f=await rpc(null,'file_begin',id,{session_hash:hash(token),request_id:r.id,file_id:fileId,name:'pending.pdf',mime:'application/pdf',bytes:12,sha256:'a'.repeat(64)});
 objects.set(f.path,Buffer.from('fixture data'));
 await service.cleanup();assert(objects.has(f.path));
 await db.query("update korlix_app_portal_files set created_at=now()-interval '11 minutes' where id=$1",[fileId]);
 await service.cleanup();assert(objects.has(f.path));
 assert.equal((await db.query('select count(*)::int n from korlix_app_portal_files where id=$1',[fileId])).rows[0].n,0);
 await db.query("update korlix_app_portal_gc set created_at=now()-interval '3 minutes' where path=$1",[f.path]);
 await service.cleanup();assert.equal(objects.has(f.path),false);
});
test('public portal shell discloses no records, blocks frames, uses strict CSP and static code only',async()=>{const id=await project();await publish(id,{name:'<script>alert(1)</script>'});const r=await fetch(base.replace('/api/app-studio','')+'/portals/'+id+'/');assert.equal(r.status,200);const html=await r.text();assert(!html.includes('Fixture business'));assert(!html.includes('alert(1)'));assert.equal(r.headers.get('referrer-policy'),'no-referrer');const csp=r.headers.get('content-security-policy');assert(csp.includes("frame-ancestors 'none'"));assert(!csp.includes('unsafe'));assert(csp.includes("connect-src 'self'"));const js=await (await fetch(base.replace('/api/app-studio','')+'/portals/assets/runtime.js')).text();assert(!/innerHTML|localStorage|sessionStorage|eval\(/.test(js));assert(js.includes("history.replaceState(null,'',location.pathname)"));});
