import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {createMetaPausedProvider,metaPausedPlan,metaCreationResources,metaCreationDigest,prepareMetaImage,MetaPausedAccessError} from '../funnels/meta_paused_provider.mjs';
const clone=v=>structuredClone(v),config={id:'1234567',secret:'private-fixture-secret',apiVersion:'v26.0'},now=Date.parse('2026-09-23T12:00:00Z');
const s={provider_name:'KORLIX 00000000-0000-4000-8000-000000000009',identity:{account:{id:'act_123',name:'Account',currency:'USD',timezone:'UTC',status:1},page:{id:'456',name:'Page',category:'Education'}},plan:{id:'00000000-0000-4000-8000-000000000003',daily_cents:2500,days:14},page:{destination:'https://example.com/f/services?utm_source=facebook&utm_medium=paid&utm_campaign=k143_00000000000040008000000000000003'},creative:{primary_text:'Plan your next step',headline:'Meet us',description:'Local support',cta:'LEARN_MORE',image_id:'00000000-0000-4000-8000-000000000007',image_alt:'Team'},image:{id:'00000000-0000-4000-8000-000000000007',sha256:'b'.repeat(64),width:600,height:400},targeting:{countries:['US','JM'],age_min:25,age_max:65,placements:'facebook_feed',categories:['NONE']},start_date:'2026-09-24',end_date:'2026-10-07',start_time:'2026-09-24T00:00:00Z',end_time:'2026-10-07T23:59:59Z',budget_acknowledged:true};
const resources={image_hash:'a'.repeat(32),campaign:'101',ad_set:'102',creative:'103',ad:'104'};
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
function mock(handler){const calls=[];const provider=createMetaPausedProvider(config,{now:()=>now,fetchImpl:async(url,options)=>{const u=new URL(url),body=Object.fromEntries(options.method==='POST'?new URLSearchParams(options.body):u.searchParams);calls.push({url:u,options,body});return response(await handler(u.pathname,body,options));}});return{provider,calls};}
test('K184 compiler fixes paused status, USD budget, Feed, traffic bidding, schedule and saved link',()=>{
 const p=metaPausedPlan(s);for(const k of ['campaign','ad_set','ad'])assert.equal(p[k].status,'PAUSED');assert.deepEqual(p.campaign.special_ad_categories,[]);assert.equal(p.campaign.objective,'OUTCOME_TRAFFIC');assert.equal(p.ad_set.daily_budget,2500);assert.equal(p.ad_set.optimization_goal,'LINK_CLICKS');assert.equal(p.ad_set.billing_event,'IMPRESSIONS');assert.equal(p.ad_set.end_time-p.ad_set.start_time,14*86400-1);assert.deepEqual(p.ad_set.targeting.geo_locations,{countries:['JM','US']});assert.deepEqual(p.ad_set.targeting.publisher_platforms,['facebook']);assert.equal(p.creative.object_story_spec.link_data.link,s.page.destination);assert.equal(JSON.stringify(p).includes('image_alt'),false);
 for(const change of [x=>x.targeting.placements='automatic',x=>x.targeting.categories=['HOUSING'],x=>x.identity.account.currency='EUR',x=>x.budget_acknowledged=false,x=>x.creative.image_id=null,x=>x.page.destination='https://wrong.test',x=>x.end_time=x.start_time]){const x=clone(s);change(x);assert.throws(()=>metaPausedPlan(x));}
});
test('K184 country, pin and explicit city/region requests are separate and stable',()=>{
 let x=clone(s);x.targeting.countries=[];x.targeting.custom_locations=[{label:'Office',latitude_micro:18000000,longitude_micro:-77000000,radius_meters:1250}];assert.deepEqual(metaPausedPlan(x).ad_set.targeting.geo_locations,{custom_locations:[{latitude:18,longitude:-77,radius:1.25,distance_unit:'kilometer'}]});delete x.targeting.custom_locations;x.targeting.geo_locations=[{key:'111',name:'Kingston',country:'JM',type:'city',region:'Kingston'},{key:'222',name:'Saint Andrew',country:'JM',type:'region',region:''}];assert.deepEqual(metaPausedPlan(x).ad_set.targeting.geo_locations,{cities:[{key:'111'}],regions:[{key:'222'}]});assert.equal(metaCreationDigest({b:2,a:1}),metaCreationDigest({a:1,b:2}));
});
test('K184 private WebP is verified by hash and dimensions before lossless PNG upload',async()=>{
 const bytes=await sharp({create:{width:600,height:400,channels:3,background:'#1799a0'}}).webp().toBuffer(),x=clone(s);x.image.sha256=createHash('sha256').update(bytes).digest('hex');const input={content:bytes.toString('base64'),width:600,height:400};const out=await prepareMetaImage(input,x);assert.equal((await sharp(out.bytes).metadata()).format,'png');assert.equal(out.sha256,createHash('sha256').update(out.bytes).digest('hex'));assert.deepEqual(await sharp(bytes).raw().toBuffer(),await sharp(out.bytes).raw().toBuffer());await assert.rejects(prepareMetaImage({...input,width:601},x));await assert.rejects(prepareMetaImage(input,s));
});
test('K184 all write bodies use fixed Graph host, bearer secret, HMAC proof and exact previous IDs',async()=>{
 const {provider:p,calls}=mock((path,b)=>b.execution_options?{success:true}:path.endsWith('/adimages')?{images:{upload:{hash:resources.image_hash}}}:{id:resources[{'campaigns':'campaign','adsets':'ad_set','adcreatives':'creative','ads':'ad'}[path.split('/').at(-1)]]});
 const prefix={};for(const stage of Object.keys(resources)){if(stage!=='image_hash')await p.validatePausedMeta('private-token',s,prefix,stage);prefix[stage]=await p.createPausedMetaResource('private-token',s,prefix,stage,Buffer.from('89504e470d0a1a0a','hex'));}assert.deepEqual(prefix,resources);assert.equal(calls.length,9);for(const c of calls){assert.equal(c.url.origin,'https://graph.facebook.com');assert(c.url.pathname.startsWith('/v26.0/act_123/'));assert.equal(c.options.headers.Authorization,'Bearer private-token');assert.equal(c.options.redirect,'error');assert.equal(c.url.search,'');assert.match(c.body.appsecret_proof,/^[a-f0-9]{64}$/);assert(!c.options.body.includes('private-token'));}
 const adset=calls.find(c=>c.url.pathname.endsWith('/adsets')&&!c.body.execution_options).body;assert.equal(adset.campaign_id,'101');assert.equal(adset.status,'PAUSED');assert.equal(adset.daily_budget,'2500');const creative=calls.find(c=>c.url.pathname.endsWith('/adcreatives')).body;assert.equal(JSON.parse(creative.object_story_spec).link_data.image_hash,resources.image_hash);const ad=calls.at(-1).body;assert.equal(ad.adset_id,'102');assert.equal(JSON.parse(ad.creative).creative_id,'103');assert.equal(ad.status,'PAUSED');
});
test('K184 permission proof requires current app, user, expiry, all scopes and Page task',async()=>{
 const debug={is_valid:true,type:'USER',app_id:config.id,user_id:'789',expires_at:now/1000+3600,data_access_expires_at:0,scopes:['ads_management','pages_show_list','pages_read_engagement','pages_manage_ads']};const page={...s.identity.page,tasks:['ADVERTISE']};
 const run=async(d=debug,pg=page)=>mock(path=>path.endsWith('/debug_token')?{data:d}:{data:[pg]}).provider.verifyCreationAccess('token','789',s.identity.page);assert.deepEqual(await run(),{verified:true});for(const patch of [{app_id:'wrong'},{user_id:'wrong'},{type:'PAGE'},{expires_at:now/1000},{data_access_expires_at:now/1000},{scopes:['ads_read']}])await assert.rejects(run({...debug,...patch}));await assert.rejects(run(debug,{...page,tasks:['ANALYZE']}));await assert.rejects(run(debug,{...page,name:'changed'}));
});
test('K184 malformed and ambiguous success, timeout, and provider details never authorize retry',async()=>{
 for(const body of [{id:123},{id:'0'},{id:'123',extra:'x'},{images:{a:{hash:resources.image_hash},b:{hash:resources.image_hash}}}]){const {provider:p,calls}=mock(()=>body);await assert.rejects(p.createPausedMetaResource('token',s,{},body.images?'image_hash':'campaign',Buffer.from('89504e470d0a1a0a','hex')));assert.equal(calls.length,1);}
 const p=createMetaPausedProvider(config,{fetchImpl:async()=>response({error:{code:190,message:'private-provider-token'}},400)});await assert.rejects(p.validatePausedMeta('token',s,{},'campaign'),e=>e instanceof MetaPausedAccessError&&!e.message.includes('private-provider-token'));let n=0;const fail=createMetaPausedProvider(config,{fetchImpl:async()=>{n++;throw Error('secret');}});await assert.rejects(fail.validatePausedMeta('token',s,{},'campaign'),e=>!e.message.includes('secret'));assert.equal(n,1);
 for(const r of [{campaign:'101'},{image_hash:resources.image_hash,ad_set:'102'},{...resources,ad:'103'},{...resources,extra:'x'}])assert.throws(()=>metaCreationResources(r));
});
function graph(snapshot=s){const p=metaPausedPlan(snapshot);return{'/v26.0/101':{...p.campaign,id:'101',account_id:'123'},'/v26.0/101/adsets':{data:[{...p.ad_set,id:'102',account_id:'123',campaign_id:'101',daily_budget:'2500',start_time:snapshot.start_time,end_time:snapshot.end_time}]},'/v26.0/101/ads':{data:[{...p.ad,id:'104',account_id:'123',campaign_id:'101',adset_id:'102',creative:{id:'103'}}]},'/v26.0/103':{...p.creative,id:'103',account_id:'123',object_story_spec:{...p.creative.object_story_spec,link_data:{...p.creative.object_story_spec.link_data,image_hash:resources.image_hash}}}};}
test('K184 recovery reads complete exact paused graph and preserves uploaded image receipt',async()=>{
 const g=graph(),{provider:p,calls}=mock(path=>g[path]);assert.deepEqual(await p.findPausedMeta('token',s,{image_hash:resources.image_hash,campaign:'101'}),resources);assert(calls.every(x=>x.options.method==='GET'));const n=calls.length;assert.equal(await p.findPausedMeta('token',s,{}),null);assert.equal(calls.length,n);
});
test('K184 recovery refuses mismatched state, budget, targeting, extra resources and changed creative',async()=>{
 for(const change of [g=>g['/v26.0/101'].status='ACTIVE',g=>g['/v26.0/101/adsets'].data[0].daily_budget='2600',g=>g['/v26.0/101/adsets'].data[0].targeting.excluded_geo_locations={countries:['CA']},g=>g['/v26.0/101/adsets'].data[0].targeting.targeting_automation.other=1,g=>g['/v26.0/101/ads'].data.push(g['/v26.0/101/ads'].data[0]),g=>g['/v26.0/101/ads'].data[0].adset_id='999',g=>g['/v26.0/103'].object_story_spec.link_data.message='changed',g=>g['/v26.0/103'].object_story_spec.link_data.call_to_action.value.extra='changed',g=>g['/v26.0/103'].object_story_spec.link_data.image_hash='b'.repeat(32)]){const g=graph();change(g);await assert.rejects(mock(path=>g[path]).provider.findPausedMeta('token',s,{image_hash:resources.image_hash,campaign:'101'}));}
 const g=graph();g['/v26.0/101/ads'].data=[];assert.equal(await mock(path=>g[path]).provider.findPausedMeta('token',s,{image_hash:resources.image_hash,campaign:'101'}),null);
});
test('K184 missing campaign receipt uses bounded exact-name scan and rejects duplicates',async()=>{
 const g=graph(),campaign=g['/v26.0/101'];let duplicate=false;const {provider:p,calls}=mock(path=>path.endsWith('/campaigns')?{data:duplicate?[campaign,campaign]:[campaign]}:g[path]);assert.deepEqual(await p.findPausedMeta('token',s,{image_hash:resources.image_hash}),resources);assert.equal(calls[0].body.limit,'100');duplicate=true;await assert.rejects(p.findPausedMeta('token',s,{image_hash:resources.image_hash}));
});
