import test from 'node:test';
import assert from 'node:assert/strict';
import {createMetaPausedProvider,metaPausedPlan} from '../funnels/meta_paused_provider.mjs';
const config={id:'1234567',secret:'private-fixture-secret',apiVersion:'v26.0'},now=Date.parse('2026-09-23T12:00:00Z');
const s={provider_name:'KORLIX 00000000-0000-4000-8000-000000000009',identity:{account:{id:'act_123',name:'Account',currency:'USD',timezone:'UTC',status:1},page:{id:'456',name:'Page',category:'Education'}},plan:{id:'00000000-0000-4000-8000-000000000003',daily_cents:2500,days:14},page:{destination:'https://example.com/f/services?utm_source=facebook&utm_medium=paid&utm_campaign=k143_00000000000040008000000000000003'},creative:{primary_text:'Plan your next step',headline:'Meet us',description:'Local support',cta:'LEARN_MORE',image_id:'00000000-0000-4000-8000-000000000007',image_alt:'Team'},image:{id:'00000000-0000-4000-8000-000000000007',sha256:'b'.repeat(64),width:600,height:400},targeting:{countries:['US','JM'],age_min:25,age_max:65,placements:'facebook_feed',categories:['NONE']},start_date:'2026-09-24',end_date:'2026-10-07',start_time:'2026-09-24T00:00:00Z',end_time:'2026-10-07T23:59:59Z',budget_acknowledged:true};
const resources={image_hash:'a'.repeat(32),campaign:'101',ad_set:'102',creative:'103',ad:'104'};
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
function mock(handler){const calls=[];const provider=createMetaPausedProvider(config,{now:()=>now,fetchImpl:async(url,options)=>{const u=new URL(url),body=Object.fromEntries(options.method==='POST'?new URLSearchParams(options.body):u.searchParams);calls.push({url:u,options,body});return response(await handler(u.pathname,body,options));}});return{provider,calls};}
function graph(snapshot=s){const p=metaPausedPlan(snapshot);return{'/v26.0/101':{...p.campaign,id:'101',account_id:'123'},'/v26.0/101/adsets':{data:[{...p.ad_set,id:'102',account_id:'123',campaign_id:'101',daily_budget:'2500',start_time:snapshot.start_time,end_time:snapshot.end_time}]},'/v26.0/101/ads':{data:[{...p.ad,id:'104',account_id:'123',campaign_id:'101',adset_id:'102',creative:{id:'103'}}]},'/v26.0/103':{...p.creative,id:'103',account_id:'123',object_story_spec:{...p.creative.object_story_spec,link_data:{...p.creative.object_story_spec.link_data,image_hash:resources.image_hash}}}};}

function activeGraph(){const g=graph();g['/v26.0/101'].effective_status='PAUSED';g['/v26.0/101/adsets'].data[0].effective_status='PAUSED';Object.assign(g['/v26.0/101/ads'].data[0],{effective_status:'PAUSED',issues_info:[],failed_delivery_checks:[],ad_review_feedback:{}});return g;}
test('K185 exact Graph status writes use only target status and validation option',async()=>{
 const {provider:p,calls}=mock(()=>({success:true}));for(const stage of ['ad','ad_set','campaign']){assert.deepEqual(await p.validateMetaControl('token',s,resources,'activate',stage),{validated:true});assert.deepEqual(await p.applyMetaControlStage('token',s,resources,'activate',stage),{confirmed:true,resource:resources[stage],stage,status:'ACTIVE'});}
 await p.applyMetaControlStage('token',s,resources,'pause','campaign');assert.equal(calls.length,7);assert.deepEqual(calls.map(c=>c.url.pathname),['/v26.0/104','/v26.0/104','/v26.0/102','/v26.0/102','/v26.0/101','/v26.0/101','/v26.0/101']);for(const c of calls){assert.equal(c.options.method,'POST');assert.equal(c.url.origin,'https://graph.facebook.com');assert.equal(c.options.redirect,'error');assert.equal(c.options.headers.Authorization,'Bearer token');assert.equal(c.body.status,c===calls.at(-1)?'PAUSED':'ACTIVE');assert.deepEqual(Object.keys(c.body).sort(),c.body.execution_options?['appsecret_proof','execution_options','status']:['appsecret_proof','status']);if(c.body.execution_options)assert.deepEqual(JSON.parse(c.body.execution_options),['validate_only']);}
 await assert.rejects(p.applyMetaControlStage('token',s,resources,'pause','ad'));await assert.rejects(p.applyMetaControlStage('token',s,resources,'delete','campaign'));assert.equal(calls.length,7);
});
test('K185 status observation proves exact account and campaign without requiring matching copy',async()=>{
 let result={id:'101',account_id:'123',name:'Renamed in Meta',status:'ACTIVE',effective_status:'WITH_ISSUES'};const {provider:p,calls}=mock(()=>result);assert.deepEqual(await p.createdMetaStatus('token',s,resources),{resource:'101',name:result.name,status:'ACTIVE',effective_status:'WITH_ISSUES'});assert.equal(calls[0].options.method,'GET');for(const patch of [{id:'999'},{account_id:'999'},{status:'UNKNOWN'},{effective_status:123}]){result={id:'101',account_id:'123',name:'Renamed in Meta',status:'ACTIVE',effective_status:'WITH_ISSUES',...patch};await assert.rejects(p.createdMetaStatus('token',s,resources));}
});
test('K185 activation inspection accepts configured children and pending Meta review without claiming approval',async()=>{
 const g=activeGraph();g['/v26.0/101/adsets'].data[0].status='ACTIVE';g['/v26.0/101/adsets'].data[0].effective_status='CAMPAIGN_PAUSED';g['/v26.0/101/ads'].data[0].effective_status='PENDING_REVIEW';const {provider:p,calls}=mock(path=>g[path]);const out=await p.inspectCreatedMeta('token',s,resources);assert.deepEqual(out.resources,resources);assert.equal(out.statuses.ad_set,'ACTIVE');assert.equal(out.effective_statuses.ad,'PENDING_REVIEW');assert.equal(out.policy,undefined);assert(calls.every(c=>c.options.method==='GET'));assert(calls.find(c=>c.url.pathname.endsWith('/ads')).body.fields.includes('failed_delivery_checks'));
});
test('K185 disapproval, missing status, billing issues and delivery/review feedback reject activation inspection',async()=>{
 for(const change of [g=>g['/v26.0/101/ads'].data[0].effective_status='DISAPPROVED',g=>g['/v26.0/101/ads'].data[0].effective_status='PENDING_BILLING_INFO',g=>delete g['/v26.0/101/ads'].data[0].effective_status,g=>g['/v26.0/101/ads'].data[0].issues_info=[{code:1}],g=>g['/v26.0/101/ads'].data[0].failed_delivery_checks=[{}],g=>g['/v26.0/101/ads'].data[0].ad_review_feedback={global:'review'},g=>g['/v26.0/101/adsets'].data[0].effective_status='WITH_ISSUES',g=>g['/v26.0/101/adsets'].data[0].daily_budget='9999',g=>g['/v26.0/103'].object_story_spec.link_data.message='changed']){const g=activeGraph();change(g);await assert.rejects(mock(path=>g[path]).provider.inspectCreatedMeta('token',s,resources));}
});
test('K185 account-only control access needs ads_management without requiring Page selection',async()=>{
 const d={is_valid:true,type:'USER',app_id:config.id,user_id:'789',expires_at:now/1000+3600,data_access_expires_at:0,scopes:['ads_management']};const {provider:p,calls}=mock(()=>({data:d}));assert.deepEqual(await p.verifyMetaControlAccess('token','789'),{verified:true});assert.equal(calls.length,1);assert(calls[0].url.pathname.endsWith('/debug_token'));d.scopes=['ads_read'];await assert.rejects(p.verifyMetaControlAccess('token','789'));
});
test('K185 ambiguous success and transport failures are sanitized and never retried',async()=>{
 for(const body of [{success:false},{success:'true'},{success:true,id:'101'},{id:'101'}]){const {provider:p,calls}=mock(()=>body);await assert.rejects(p.applyMetaControlStage('token',s,resources,'pause','campaign'));assert.equal(calls.length,1);}
 let calls=0;const p=createMetaPausedProvider(config,{fetchImpl:async()=>{calls++;throw Error('private token');}});await assert.rejects(p.applyMetaControlStage('token',s,resources,'activate','ad'),e=>!e.message.includes('private token'));assert.equal(calls,1);
});
