import {fail,id} from '../bookkeeping/core.mjs';
import {buildReports} from '../bookkeeping/reports.mjs';
export const CHECKLIST={
 identity:'Identity, household and dependent details held securely',prior_return:'Prior-year returns and carryover records',wages:'W-2 wage statements',contractor:'1099-NEC / 1099-K and other business income records',investments:'Interest, dividends, investments and digital asset records',retirement:'Retirement, Social Security and benefit statements',property:'Rental, property sale and mortgage records',deductions:'Education, health coverage, charitable and other deduction records',payments:'Estimated payments, withholding and extension payments',business_records:'Business receipts, invoices and statement review',assets:'Equipment, depreciation, inventory and loan records',state_local:'State, local and other-country filing requirements checked with preparer'
};
export const STATUSES={needed:'To gather',ready:'Organized',not_applicable:'Not applicable'};
export const REVIEW={pending:'Needs review',reviewed:'Reviewed',ask_preparer:'Ask preparer'};
export const FILING={not_chosen:'Not chosen',single:'Single',married_joint:'Married filing jointly',married_separate:'Married filing separately',head_household:'Head of household',qualifying_survivor:'Qualifying surviving spouse'};
export const STATES='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
export const SOURCES=[{label:'IRS recordkeeping guidance',url:'https://www.irs.gov/publications/p583'},{label:'Schedule C instructions (2025)',url:'https://www.irs.gov/instructions/i1040sc'},{label:'IRS business structures',url:'https://www.irs.gov/businesses/small-businesses-self-employed/business-structures'},{label:'IRS filing provider requirements',url:'https://www.irs.gov/e-file-providers/electronic-return-originator-ero-technical-fact-sheet'}];
export const SCOPE='U.S. preparation organizer using recorded USD calendar-year books. Amounts are book figures, not taxable income, allowed deductions, liability or a filed return. Personal and separate-entity records are not combined. Confirm completeness, tax treatment, tax year and adjustments with your preparer. No automatic filing or external sharing.';
const text=(v,n,label)=>{if(typeof v!=='string'||v.length>n||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))fail(`${label} must be text up to ${n} characters.`);return v.trim();};
const object=v=>{if(!v||typeof v!=='object'||Array.isArray(v))fail('Invalid organizer fields.');return v;};
const keys=(v,allowed)=>{if(Object.keys(v).some(k=>!allowed.includes(k)))fail('Unexpected organizer field. Refresh and try again.');};
export const defaults=()=>({filingStatus:'not_chosen',states:[],notes:'',checklist:Object.fromEntries(Object.keys(CHECKLIST).map(k=>[k,'needed'])),reviews:{}});
export function organizer(v){object(v);keys(v,['filingStatus','states','notes','checklist','reviews']);if(!Object.hasOwn(FILING,v.filingStatus))fail('Choose an expected filing status.');if(!Array.isArray(v.states)||v.states.length>10||new Set(v.states).size!==v.states.length||v.states.some(s=>!STATES.includes(s)))fail('Choose up to ten U.S. states.');object(v.checklist);keys(v.checklist,Object.keys(CHECKLIST));const checklist={};for(const k of Object.keys(CHECKLIST)){if(!Object.hasOwn(STATUSES,v.checklist[k]))fail('Choose a status for each checklist item.');checklist[k]=v.checklist[k];}object(v.reviews);if(Object.keys(v.reviews).length>25)fail('Too many business reviews.');const reviews={};for(const [b,accounts]of Object.entries(v.reviews)){id(b);object(accounts);if(Object.keys(accounts).length>150)fail('Too many account reviews.');reviews[b]={};for(const [code,r]of Object.entries(accounts)){if(!/^[1-5]\d{3}$/.test(code))fail('Invalid review account.');object(r);keys(r,['status','note']);if(!Object.hasOwn(REVIEW,r.status))fail('Choose a review status.');reviews[b][code]={status:r.status,note:text(r.note,500,'Review note')};}}return {filingStatus:v.filingStatus,states:[...v.states].sort(),notes:text(v.notes,2000,'Preparer notes'),checklist,reviews};}
export function links(v){if(!Array.isArray(v)||v.length>25)fail('Choose up to 25 of your own businesses.');const ids=v.map(id);if(new Set(ids).size!==ids.length)fail('Each business can be linked once.');return ids.sort();}
export function version(v){if(!Number.isSafeInteger(v)||v<1)fail('Refresh the organizer before saving.');return v;}
export function taxYear(v){if(!Number.isSafeInteger(v)||v<2000||v>new Date().getUTCFullYear()+1)fail('Choose an available calendar year.');return v;}
const notes={sole_proprietor:'Sole-proprietor preparation: review Schedule C applicability and any required additional schedules.',partnership:'Separate partnership preparation: do not treat business profit as an owner’s individual taxable income.',s_corporation:'Separate S corporation preparation: review entity records and owner schedules with your preparer.',c_corporation:'Separate C corporation preparation: corporate income and the owner’s personal return stay separate.',unsure:'Tax treatment needs confirmation before selecting a return type.'};
export function present(raw){const w=raw.workspace;const books=w.books.map(b=>{const r=buildReports(b.report);const reviews=w.data.reviews[r.business.id]??{};const accounts=r.accounts.map(a=>{const value=['income','liability','equity'].includes(a.kind)?BigInt(a.kind==='income'?a.period_credit_cents:a.closing_cents)*(a.kind==='income'?1n:-1n)-(a.kind==='income'?BigInt(a.period_debit_cents):0n):BigInt(a.kind==='expense'?a.period_debit_cents:a.closing_cents)-(a.kind==='expense'?BigInt(a.period_credit_cents):0n);return {...a,book_cents:String(value),review:reviews[a.code]??{status:'pending',note:''}};}).filter(a=>BigInt(a.period_debit_cents)!==0n||BigInt(a.period_credit_cents)!==0n||(['cash','asset','liability','equity'].includes(a.kind)&&BigInt(a.closing_cents)!==0n)||a.review.note||a.review.status!=='pending');return {business:r.business,summary:r.summary,accounts,warnings:r.warnings,opening:r.opening,firstRecordedDate:r.first_recorded_date,cashEntryCount:r.cash_entry_count,journalCount:r.journal_count,mileage:b.mileage,receipts:b.receipts,treatmentNote:notes[r.business.tax_treatment]??notes.unsure};});const checklist=Object.values(w.data.checklist),reviewAccounts=books.flatMap(b=>b.accounts);return {workspace:{id:w.id,year:w.tax_year,country:w.country,version:w.version,businessIds:w.business_ids,data:w.data,books,fingerprint:w.fingerprint,snapshotAt:w.snapshot_at,updatedAt:w.updated_at},stale:raw.stale??false,checkedAt:raw.checkedAt??null,progress:{organized:checklist.filter(s=>s==='ready').length,notApplicable:checklist.filter(s=>s==='not_applicable').length,toGather:checklist.filter(s=>s==='needed').length,accountsToReview:reviewAccounts.filter(a=>a.review.status!=='reviewed').length},scope:SCOPE,filingEnabled:false,sources:SOURCES};}
export function validateReviews(data,w){for(const [b,accounts]of Object.entries(data.reviews)){const book=w.books.find(x=>x.report.business.id===b);if(!book)fail('Only linked businesses can be reviewed.');for(const code of Object.keys(accounts))if(!book.report.accounts.some(a=>a.code===code))fail('This review account was not found in the saved books.');}}
export const dollars=v=>{const n=BigInt(v),a=n<0n?-n:n;return `${n<0n?'-':''}${a/100n}.${String(a%100n).padStart(2,'0')}`;};
export function packetCsv(p){const w=p.workspace;const rows=[['KORLIX TAX PREPARATION ORGANIZER'],['Tax year',String(w.year)],['Period','Calendar year; confirm fiscal-year requirements separately'],['Country','United States'],['Revision',String(w.version)],['Book snapshot',w.snapshotAt],['Source check',p.checkedAt??'See export revision'],['Scope',SCOPE],['Expected filing status (unverified)',FILING[w.data.filingStatus]],['States to discuss',w.data.states.join(', ')],['Preparer notes',w.data.notes],[],['PERSONAL / DOCUMENT ORGANIZER','Status'],...Object.entries(CHECKLIST).map(([k,label])=>[label,STATUSES[w.data.checklist[k]]]),[]];for(const b of w.books){rows.push(['BUSINESS',b.business.name],['Business ID',b.business.id],['Legal structure',b.business.legal_structure],['Recorded tax treatment',b.business.tax_treatment],['Treatment review',b.treatmentNote],['Recorded income USD',{numeric:dollars(b.summary.income_cents)}],['Recorded expenses USD',{numeric:dollars(b.summary.expense_cents)}],['Recorded net USD (not taxable income)',{numeric:dollars(b.summary.net_cents)}],['Recorded active mileage (no deduction calculated)',`${BigInt(b.mileage.distance_tenths)/10n}.${BigInt(b.mileage.distance_tenths)%10n}`],['Expenses without a linked receipt',String(b.receipts.without_receipt)],...b.warnings.map(x=>['Review',x]),['Type','Account','Name','Book amount USD','Review status','Review note']);for(const a of b.accounts)rows.push([a.kind,a.code,a.name,{numeric:dollars(a.book_cents)},REVIEW[a.review.status],a.review.note]);rows.push([]);}rows.push(['GUIDANCE SOURCES (verify the applicable tax year)'],...SOURCES.map(s=>[s.label,s.url]));const cell=v=>{let s=v&&typeof v==='object'&&/^-?\d+\.\d{2}$/.test(v.numeric)?v.numeric:String(v??'');if(!(v&&typeof v==='object')&&(/^\s*[=+\-@]/.test(s)||/^[\t\r\n]/.test(s)))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return {filename:`KORLIX-Tax-Prep-${w.year}-r${w.version}.csv`,csv:'\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n'};}
