import {fail,id} from '../bookkeeping/core.mjs';
import {CHECKLIST,STATUSES,REVIEW,FILING,STATES,SOURCES,SCOPE,defaults,organizer,links,version,taxYear,present,validateReviews,packetCsv} from './core.mjs';
export function registerTaxPrepRoutes(app,{route,database}){
 const rpc=async(actor,action,workspace=null,data={})=>{const r=await database.rpc('korlix_tax_prep_v1',{p_actor:actor,p_action:action,p_id:workspace,p_data:data});if(r.error){const e=r.error,status={P0002:404,'40001':409,'23505':409,'54000':422,P0001:400,'42501':403,'23514':400,'23502':400,'22P02':400}[e.code]??503;fail(['P0002','40001','54000','P0001'].includes(e.code)?e.message:'Tax Prep could not finish this request. Refresh before retrying.',status,'TAX_PREP_ERROR');}if(!r.data)fail('Tax Prep is temporarily unavailable.',503);return r.data;};
 const base='/api/bookkeeping/tax-prep';
 app.get(base,route(async(_q,r,u)=>r.json({...await rpc(u,'list'),checklist:CHECKLIST,checklistStatuses:STATUSES,reviewStatuses:REVIEW,filingStatuses:FILING,states:STATES,sources:SOURCES,scope:SCOPE,filingEnabled:false,currentYear:new Date().getUTCFullYear()})));
 app.post(base,route(async(q,r,u)=>{const p={year:taxYear(q.body?.year),business_ids:links(q.body?.business_ids??[]),data:defaults()};const w=await rpc(u,'create',id(q.body?.request_key),p);r.status(201).json(present(w));}));
 app.get(base+'/:id',route(async(q,r,u)=>r.json(present(await rpc(u,'get',id(q.params.id))))));
 app.put(base+'/:id',route(async(q,r,u)=>{const wid=id(q.params.id),data=organizer(q.body?.data),p={version:version(q.body?.version),request_key:id(q.body?.request_key),data};const current=await rpc(u,'get',wid);validateReviews(data,current.workspace);const saved=await rpc(u,'save',wid,p);r.json(present({...saved,stale:current.stale}));}));
 app.post(base+'/:id/books',route(async(q,r,u)=>{if(q.body?.confirmed!==true)fail('Confirm the book refresh and review reset.');const p={version:version(q.body?.version),request_key:id(q.body?.request_key),business_ids:links(q.body?.business_ids),confirmed:true};r.json(present(await rpc(u,'books',id(q.params.id),p)));}));
 app.post(base+'/:id/export',route(async(q,r,u)=>{const format=q.body?.format;if(!['csv','packet'].includes(format))fail('Choose PDF packet or CSV export.');if(typeof q.body?.fingerprint!=='string'||!/^[a-f0-9]{64}$/.test(q.body.fingerprint))fail('Refresh the books before exporting.');const p=present(await rpc(u,'export',id(q.params.id),{version:version(q.body?.version),fingerprint:q.body.fingerprint}));r.json(format==='csv'?{...packetCsv(p),year:p.workspace.year,version:p.workspace.version}:{packet:p,filename:`KORLIX-Tax-Prep-${p.workspace.year}-r${p.workspace.version}.pdf`});}));
 app.delete(base+'/:id',route(async(q,r,u)=>{if(q.body?.confirmed!==true)fail('Confirm before removing this organizer.');r.json(await rpc(u,'delete',id(q.params.id),{version:version(q.body?.version),confirmed:true}));}));
}
