import {readFileSync} from 'node:fs';
const runtime=readFileSync(new URL('./runtime.js',import.meta.url),'utf8');
const css=readFileSync(new URL('./runtime.css',import.meta.url),'utf8');
export function exportFiles(spec,id,version,preview=false){
 const data=JSON.stringify(spec).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'; object-src 'none'"><title>KORLIX app prototype</title><style>${css}</style></head><body><div id="app"></div><script type="application/json" id="app-spec">${data}</script><script>const IS_PREVIEW=${JSON.stringify(preview)};const STORAGE_KEY=${JSON.stringify('korlix-app-'+id+'-v'+version)};\n${runtime}</script></body></html>`;
 const readme=`# ${spec.name}\n\nCreated with KORLIX App Studio. Version ${version}.\n\n## Run it\nOpen index.html in a modern browser, or serve this folder with a static web server. There are no packages, build tools or API keys. The HTML includes all styles and JavaScript; runtime.js and runtime.css are also supplied separately for editing.\n\n## What works\nCollection navigation, search, add/edit/delete, required fields, choice fields, dates, numbers, checkboxes and status boards. All initial records are fictional samples. Your entries are saved only in this browser when local storage is available. A notice appears if saving is unavailable. Use Export data regularly; clearing browser storage removes your entries. Each exported app version has separate storage.\n\n## Before a public launch\nThis is a local prototype, not a multi-user service. It does not provide real login, account security, shared database, payments, messaging, live integrations, native-store packages or deployment. Never enter sensitive production data. Connect and test the needed backend services before inviting customers. A static host can serve this folder, but hosting alone does not add those services.\n\n## App plan\n${spec.description}\n\n${spec.nextSteps.map(s=>'- '+s).join('\n')}\n\n## Editing\napp.json is the structured app definition. To change the exported app manually, edit the app-spec JSON inside index.html and review the embedded style/script. Text is rendered with DOM textContent; no user HTML or generated code is executed. Keep that property if you extend the renderer.\n\nGenerated app idea and sample schema were reviewed for structure, not independently verified for every business requirement. Test your own workflows before relying on this app.\n`;
 return {'index.html':html,'app.json':JSON.stringify(spec,null,2)+'\n','runtime.js':runtime,'runtime.css':css,'README.md':readme};
}
function crc32(b){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
// Five bounded UTF-8 source files, stored without compression. No file paths are user-controlled.
export function zipFiles(files){const parts=[],central=[];let offset=0;for(const [path,value] of Object.entries(files)){const name=Buffer.from(path),body=Buffer.from(value),crc=crc32(body),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(33,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(body.length,18);local.writeUInt32LE(body.length,22);local.writeUInt16LE(name.length,26);parts.push(local,name,body);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x0800,8);c.writeUInt16LE(33,14);c.writeUInt32LE(crc,16);c.writeUInt32LE(body.length,20);c.writeUInt32LE(body.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);central.push(c,name);offset+=local.length+name.length+body.length;}const cb=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(cb.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,cb,end]);}
