/* Customer portal runtime: trusted fixed workflow, DOM text nodes, no generated code. */
(()=>{
 'use strict';
 const config=JSON.parse(document.getElementById('portal-config').textContent),root=document.getElementById('app'),base='/api/app-studio/portals/'+config.id+'/runtime';
 let token=null,portal=null,all=[],filter='all',search='',busy=false,requestKey=null,replyKey=null;
 const labels={open:'New',in_progress:'In progress',waiting:'Waiting for customer',completed:'Completed',cancelled:'Cancelled'};
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
 const button=(label,fn,cls='')=>{const n=el('button',label,cls);n.type='button';n.addEventListener('click',()=>guard(fn,n));return n;};
 const link=(label,url,cls='button')=>{const a=el('a',label,cls);a.href=url;return a;};
 const date=s=>new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
 const clear=()=>{root.replaceChildren();document.title=portal?portal.name+' · KORLIX':'KORLIX Customer Portal';};
 function error(e){const old=document.getElementById('portal-error');old?.remove();const n=el('div',e.message||'This action could not finish. Refresh and retry.','error');n.id='portal-error';n.setAttribute('role','alert');root.prepend(n);n.scrollIntoView?.({block:'nearest'});}
 async function guard(fn,node){if(busy)return;busy=true;if(node)node.disabled=true;try{await fn();}catch(e){error(e);}finally{busy=false;if(node)node.disabled=false;}}
 async function api(path='',{method='GET',body,raw=false}={}){const headers={};if(token)headers.Authorization='Portal '+token;if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch(base+path,{method,credentials:'omit',cache:'no-store',headers,...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});if(!response.ok){let message='The portal could not finish this request.';try{message=(await response.json()).error||message;}catch{}if(response.status===403){token=null;gate('Your portal session ended or access changed. Open it from KORLIX again.');}throw Error(message);}return raw?response.blob():response.json();}
 function gate(message='Sign in to KORLIX to open this private customer portal.'){clear();const box=el('section',undefined,'card dialog');box.append(el('div','KORLIX CUSTOMER PORTAL','eyebrow'),el('h1','Your work, in one place.'),el('p',message),link('Continue with KORLIX',config.signInUrl),el('p','An invitation from the business owner is required. Your requests and attachments stay private.','muted'));root.append(box);}
 function header(back){const h=el('section',undefined,'hero'),ey=el('div','KORLIX · CUSTOMER PORTAL','eyebrow');h.append(ey,el('h1',portal.name),el('p',portal.description),el('span',portal.role==='customer'?'Your private workspace':portal.role==='owner'?'Owner workspace':'Staff workspace','badge'));const tools=el('div',undefined,'toolbar');if(back)tools.append(button('← All requests',load,'secondary'));else tools.append(el('p','Shared with your business team.','muted'));tools.append(button('Sign out of portal',async()=>{await api('/logout',{method:'POST'});token=null;portal=null;gate('You have signed out of this portal.');},'secondary'));h.append(tools);root.append(h);document.documentElement.className=portal.theme==='dark'?'dark':'';document.documentElement.style.setProperty('--accent',/^#[0-9a-f]{6}$/i.test(portal.accent)?portal.accent:'#414ada');}
 async function load(){const d=await api();portal=d.portal;all=d.requests;list();}
 function list(){clear();header(false);const tools=el('div',undefined,'toolbar'),controls=el('div',undefined,'row');const searchBox=el('input');searchBox.type='search';searchBox.placeholder='Search requests';searchBox.setAttribute('aria-label','Search requests');searchBox.value=search;searchBox.addEventListener('input',()=>{search=searchBox.value;cards();});const select=el('select');select.setAttribute('aria-label','Filter by status');for(const [v,l] of [['all','All statuses'],...Object.entries(labels)]){const o=el('option',l);o.value=v;select.append(o);}select.value=filter;select.addEventListener('change',()=>{filter=select.value;cards();});controls.append(searchBox,select);tools.append(controls,button('＋ New request',newRequest),button('Refresh',load,'secondary'));root.append(tools);const grid=el('div',undefined,'grid');grid.id='requests';root.append(grid);cards();if(portal.payment_url){const pay=el('section',undefined,'card');pay.append(el('h2','Payments'),el('p','The business has provided an external checkout link. Payment details and receipts are handled by that provider, and payment status is not tracked here.','muted'));const checkout=link('Open external checkout',portal.payment_url,'button secondary');checkout.target='_blank';checkout.rel='noopener noreferrer';pay.append(checkout);const foot=el('div',undefined,'toolbar');foot.append(pay);root.append(foot);}}
 function cards(){const grid=document.getElementById('requests');grid.replaceChildren();const shown=all.filter(r=>(filter==='all'||r.status===filter)&&[r.title,r.description,r.customer_email].join(' ').toLowerCase().includes(search.toLowerCase()));if(!shown.length){const e=el('div',undefined,'card empty');e.append(el('h2',all.length?'No matching requests':'Let’s get started'),el('p',all.length?'Try another search or status.':'Send your first request and keep updates, replies and attachments together.','muted'));grid.append(e);return;}for(const r of shown){const c=el('article',undefined,'card');c.append(el('span',labels[r.status],'badge '+r.status),el('h2',r.title),el('p',r.description.length>170?r.description.slice(0,170)+'…':r.description));if(portal.role!=='customer')c.append(el('p',r.customer_email,'muted'));c.append(el('p','Updated '+date(r.updated_at),'muted small'),button('Open request',()=>detail(r.id),'secondary'));grid.append(c);}}
 function field(form,label,{multiline=false,max=160,required=true}={}){const l=el('label',label),n=el(multiline?'textarea':'input');n.maxLength=max;n.required=required;l.append(n);form.append(l);return n;}
 function newRequest(){clear();header(true);requestKey=crypto.randomUUID();const c=el('section',undefined,'card'),f=el('form');c.append(el('h2','New request'),el('p','Tell the business what you need. You can attach photos or a PDF after submitting.','muted'));const title=field(f,'Request title',{max:160}),description=field(f,'Details',{multiline:true,max:6000});const submit=el('button','Submit request');submit.type='submit';f.append(submit);f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;guard(async()=>{const d=await api('/requests',{method:'POST',body:{request_key:requestKey,title:title.value.trim(),description:description.value.trim()}});await detail(d.request.id);},submit);});c.append(f);root.append(c);title.focus();}
 async function detail(id){const d=await api('/requests/'+id),r=d.request;clear();header(true);const layout=el('div',undefined,'split'),main=el('section',undefined,'stack'),aside=el('aside',undefined,'stack');const overview=el('div',undefined,'card');overview.append(el('span',labels[r.status],'badge '+r.status),el('h2',r.title),el('p',r.description,'details'),el('p','Submitted '+date(r.created_at)+' · '+r.customer_email,'muted small'));main.append(overview);
  const conversation=el('section',undefined,'card stack');conversation.append(el('h2','Conversation'));if(!d.messages.length)conversation.append(el('p','No replies yet. Add a message to keep the conversation moving.','muted'));for(const m of d.messages){const row=el('article',undefined,'message');row.append(el('strong',m.author_role==='customer'?'Customer':'Business team'),el('div',date(m.created_at),'muted small'),el('p',m.body));conversation.append(row);}const f=el('form'),reply=field(f,'Reply',{multiline:true,max:6000}),send=el('button','Send reply');send.type='submit';f.append(send);replyKey=crypto.randomUUID();f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;guard(async()=>{await api('/requests/'+id+'/messages',{method:'POST',body:{request_key:replyKey,body:reply.value.trim()}});await detail(id);},send);});conversation.append(f);main.append(conversation);
  if(portal.role!=='customer'){const status=el('section',undefined,'card'),select=el('select');select.setAttribute('aria-label','Request status');for(const [v,l] of Object.entries(labels)){const o=el('option',l);o.value=v;select.append(o);}select.value=r.status;status.append(el('h2','Update status'),select,el('p','Status changes are visible to the customer.','muted'),button('Save status',async()=>{await api('/requests/'+id+'/status',{method:'PUT',body:{version:r.version,status:select.value}});await detail(id);}));aside.append(status);}
  const files=el('section',undefined,'card');files.append(el('h2','Attachments'),el('p','Up to 10 files per request. JPG, PNG, WEBP or PDF, 5 MB each. Photos are resized and metadata is removed.','muted small'));if(!d.files.length)files.append(el('p','No attachments yet.','muted'));for(const file of d.files){const row=el('div',undefined,'file');row.append(el('strong',file.name),el('p',Math.ceil(file.bytes/1024)+' KB','muted small'));const actions=el('div',undefined,'row');actions.append(button('Download',async()=>{const b=await api('/files/'+file.id,{raw:true}),url=URL.createObjectURL(b),a=link('',url);a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);},'secondary'));if(portal.role!=='customer'||file.author_id===r.customer_id)actions.append(button('Remove',()=>confirmAction('Remove this attachment?',async()=>{await api('/files/'+file.id,{method:'DELETE',body:{confirmed:true}});await detail(id);},()=>detail(id)),'secondary'));row.append(actions);files.append(row);}
  const input=el('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,application/pdf';input.setAttribute('aria-label','Choose attachment');const upload=button('Upload attachment',async()=>{const file=input.files?.[0];if(!file)throw Error('Choose a photo or PDF first.');if(file.size>5242880)throw Error('Choose a file smaller than 5 MB.');const body=new FormData();body.append('file',file);await api('/requests/'+id+'/files',{method:'POST',body});await detail(id);});if(d.files.length>=10){input.disabled=true;upload.disabled=true;}files.append(input,el('div','', 'toolbar'),upload);aside.append(files);
  if(portal.role!=='customer'){const remove=el('section',undefined,'card');remove.append(el('h3','Remove request'),el('p','Permanently removes its conversation and attachments.','muted small'),button('Delete request',()=>confirmAction('Delete this request and all of its attachments?',async()=>{await api('/requests/'+id,{method:'DELETE',body:{version:r.version,confirmed:true}});await load();},()=>detail(id)),'danger'));aside.append(remove);}
  layout.append(main,aside);root.append(layout);
 }
 function confirmAction(message,yes,no){clear();header(false);const c=el('section',undefined,'card dialog'),row=el('div',undefined,'row');c.append(el('h2',message),el('p','This cannot be undone.','muted'));row.append(button('Confirm',yes,'danger'),button('Cancel',no,'secondary'));c.append(row);root.append(c);}
 const params=new URLSearchParams(location.hash.slice(1)),launch=params.get('launch');history.replaceState(null,'',location.pathname);
 if(launch&&/^[A-Za-z0-9_-]{43}$/.test(launch))void (async()=>{try{const d=await api('/exchange',{method:'POST',body:{code:launch}});token=d.token;portal=d.portal;await load();}catch(e){token=null;portal=null;gate(e.message);}})();else gate();
})();
