'use strict';
(() => {
 const spec=JSON.parse(document.getElementById('app-spec').textContent),root=document.getElementById('app');
 const initial=()=>Object.fromEntries(spec.collections.map(c=>[c.id,c.records.map(r=>({id:r.id,...Object.fromEntries(r.values.map(v=>[v.fieldId,v.value]))}))]));
 let data=initial(),page='home',query='',filter='',storageOk=true;
 try{const saved=IS_PREVIEW?null:JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&spec.collections.every(c=>Array.isArray(saved[c.id])&&saved[c.id].length<=2000&&saved[c.id].every(r=>r&&typeof r.id==='string'&&c.fields.every(f=>typeof r[f.id]==='string'))))data=saved;}catch{storageOk=false;}
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=String(text);if(cls)e.className=cls;return e;};
 const button=(label,fn,cls)=>{const b=el('button',label,cls);b.type='button';b.addEventListener('click',fn);return b;};
 const save=()=>{if(IS_PREVIEW)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));storageOk=true;}catch{storageOk=false;}};
 const ask=message=>new Promise(resolve=>{const d=el('dialog'),a=el('div',null,'actions');d.append(el('p',message));a.append(button('Cancel',()=>{resolve(false);d.close();}),button('Confirm',()=>{resolve(true);d.close();},'primary'));d.append(a);document.body.append(d);d.addEventListener('cancel',()=>resolve(false));d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();});
 const go=id=>{page=id;query='';filter='';render();};
 const pretty=(f,v)=>f.type==='checkbox'?(v==='true'?'Yes':'No'):(v||'—');
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({app:spec.name,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='app-data.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function edit(c,row){
  const dialog=el('dialog'),form=el('form'),controls=new Map();form.append(el('h2',(row?'Edit ':'Add ')+c.singular));
  for(const f of c.fields){const label=el('label',f.label+(f.required?' *':''),f.type==='checkbox'?'check':'');let input;
   if(f.type==='select'){input=el('select');input.append(new Option('Choose…',''));for(const o of f.options)input.append(new Option(o,o));}
   else if(f.type==='text'){input=el('input');input.type='text';input.maxLength=600;}
   else{input=el('input');input.type=f.type==='checkbox'?'checkbox':f.type==='number'?'number':'date';if(f.type==='number'){input.step='any';input.min='-999999999999';input.max='999999999999';}}
   if(f.type==='checkbox')input.checked=row?.[f.id]==='true';else input.value=row?.[f.id]||'';
   input.required=f.required;input.addEventListener('input',()=>input.setCustomValidity(''));label.append(input);form.append(label);controls.set(f.id,input);
  }
  const actions=el('div',null,'actions');actions.append(button('Cancel',()=>dialog.close()));const submit=el('button','Save '+c.singular,'primary');submit.type='submit';actions.append(submit);form.append(actions);
  form.addEventListener('submit',e=>{e.preventDefault();for(const f of c.fields){const input=controls.get(f.id);if(f.required&&f.type!=='checkbox'&&!input.value.trim())input.setCustomValidity('Enter '+f.label.toLowerCase()+'.');}if(!form.reportValidity())return;const next={id:row?.id||('r_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2))};for(const f of c.fields)next[f.id]=f.type==='checkbox'?String(controls.get(f.id).checked):controls.get(f.id).value.trim();if(row)data[c.id]=data[c.id].map(r=>r.id===row.id?next:r);else{if(data[c.id].length>=2000){alert('Export your data before adding more than 2,000 records.');return;}data[c.id].push(next);}save();dialog.close();render();});
  dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();
 }
 function card(c,row){const card=el('article',null,'card');card.append(el('h3',row[c.fields[0].id]||c.singular));const dl=el('dl');for(const f of c.fields.slice(1)){dl.append(el('dt',f.label),el('dd',pretty(f,row[f.id])));}card.append(dl);const actions=el('div',null,'actions');actions.append(button('Edit',()=>edit(c,row)),button('Delete',async()=>{if(await ask('Delete this '+c.singular.toLowerCase()+'?')){data[c.id]=data[c.id].filter(r=>r.id!==row.id);save();render();}},'danger'));card.append(actions);return card;}
 function renderRecords(c,container){container.replaceChildren();let rows=data[c.id].filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(query.toLowerCase())));const status=c.fields.find(f=>f.type==='select');if(filter&&status)rows=rows.filter(r=>r[status.id]===filter);if(!rows.length){const empty=el('div',null,'empty');empty.append(el('h3','No records here yet'),el('p',query||filter?'Try another search or clear the filter.':'Add your first '+c.singular.toLowerCase()+'.'));container.append(empty);return;}
  if(c.layout==='board'&&status){container.className='board';for(const value of [...status.options,'']){const grouped=rows.filter(r=>(r[status.id]||'')===value);if(!grouped.length)continue;const col=el('section',null,'column');col.append(el('h3',(value||'Unassigned')+' · '+grouped.length));for(const r of grouped)col.append(card(c,r));container.append(col);}}
  else{container.className='grid';for(const r of rows)container.append(card(c,r));}
 }
 function render(){root.replaceChildren();document.title=spec.name;document.documentElement.style.setProperty('--accent',spec.accent);const rgb=[1,3,5].map(n=>parseInt(spec.accent.slice(n,n+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),lum=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;document.documentElement.style.setProperty('--on-accent',lum>.179?'#000':'#fff');document.body.classList.toggle('dark',spec.theme==='dark');const header=el('header'),brand=el('div');brand.append(el('strong',spec.name),el('small',IS_PREVIEW?'Interactive preview · sample data':'Your local workspace'));header.append(brand);if(!IS_PREVIEW)header.append(button('Export data',download));root.append(header);const nav=el('nav');nav.setAttribute('aria-label','App sections');nav.append(button('Overview',()=>go('home'),page==='home'?'active':''));for(const c of spec.collections)nav.append(button(c.label,()=>go(c.id),page===c.id?'active':''));root.append(nav);const main=el('main');root.append(main);
  if(!storageOk)main.append(el('p','Browser saving is unavailable. Changes may be lost when you close this page. Export data to keep a copy.','notice storage-warning'));
  if(page==='home'){const hero=el('section',null,'hero');hero.append(el('h1',spec.tagline),el('p',spec.description));main.append(hero);const grid=el('div',null,'grid');for(const c of spec.collections){const tile=el('section',null,'card');tile.append(el('span',data[c.id].length,'metric'),el('h3',c.label),button('Open '+c.label,()=>go(c.id),'primary'));grid.append(tile);}main.append(grid);}
  else{const c=spec.collections.find(c=>c.id===page),toolbar=el('div',null,'toolbar');toolbar.append(el('h1',c.label),button('Add '+c.singular,()=>edit(c,null),'primary'));main.append(toolbar);const tools=el('div',null,'tools'),search=el('input');search.type='search';search.placeholder='Search '+c.label.toLowerCase();search.setAttribute('aria-label',search.placeholder);search.value=query;const records=el('div');search.addEventListener('input',()=>{query=search.value;renderRecords(c,records);});tools.append(search);const status=c.fields.find(f=>f.type==='select');if(status){const select=el('select');select.setAttribute('aria-label','Filter '+status.label);select.append(new Option('All '+status.label.toLowerCase(),''));for(const v of status.options)select.append(new Option(v,v));select.value=filter;select.addEventListener('change',()=>{filter=select.value;renderRecords(c,records);});tools.append(select);}main.append(tools,el('div',null,'toolbar'),records);renderRecords(c,records);}
  const footer=el('footer');footer.append(el('p',IS_PREVIEW?'Preview entries are temporary and reset when the preview reloads.':'Built with KORLIX · Local prototype · Data stays in this browser. Initial records are fictional samples.'),button('Reset sample data',async()=>{if(await ask('Replace all your local entries with the original sample records? Export data first if you need a copy.')){data=initial();save();render();}}));root.append(footer);
 }
 render();
})();
