import {validateLesson,fail} from './model.mjs';
const section=(heading,body,example,takeaway)=>({heading,body,example,takeaway});
const card=(front,back)=>({front,back});
const q=(question,options,answer,hint,explanation)=>({question,options,answer,hint,explanation});
const packs={
 percentages:{title:'Percentages you can actually use',summary:'Find a percentage, work out a discount and compare a change using everyday examples.',objectives:['Convert between percentages and decimals.','Calculate part of a whole and percentage changes.'],sections:[
  section('Percent means “out of 100”','A percentage describes a quantity relative to a whole. Divide a percentage by 100 to write it as a decimal. Multiply a decimal by 100 to write it as a percentage.','25% = 25 ÷ 100 = 0.25. A quarter of something is 25%.','25% and 0.25 represent the same proportion.'),
  section('Find the part, then the final amount','To find a percentage of an amount, multiply the amount by the percentage as a decimal. For a discount, subtract that part from the original amount.','A $60 jacket is 20% off. The discount is 60 × 0.20 = $12. The sale price is 60 − 12 = $48.','The discount amount and the sale price are different numbers.'),
  section('Measure change from the starting value','Percentage change = (new value − original value) ÷ original value × 100. The original value must be nonzero. A positive result is an increase; a negative result is a decrease.','A price rises from $40 to $50. The change is $10. 10 ÷ 40 × 100 = 25%, so the increase is 25%.','Divide by the original value, not the new value.')],cards:[
  card('What does 15% mean?','15 out of every 100, or 0.15.'),card('How do you find 10% of an amount?','Divide it by 10, or multiply it by 0.10.'),card('What is the sale price after a 20% discount on $60?','$48. The discount is $12.'),card('Which value is the denominator in percentage change?','The original value, which must not be zero.')],quiz:[
  q('What is 25% as a decimal?',['2.5','0.25','25','0.025'],1,'Divide by 100.','25 ÷ 100 = 0.25. Moving only one decimal place would give 2.5.'),
  q('What is 15% of 80?',['8','15','12','65'],2,'Use 0.15 as the multiplier.','80 × 0.15 = 12. You can also add 10% of 80 (8) and 5% (4).'),
  q('A $50 item is discounted by 10%. What is the sale price?',['$45','$5','$40','$55'],0,'Subtract the discount from the original price.','The discount is $5, so the sale price is $50 − $5 = $45.'),
  q('A value increases from 20 to 25. What is its percentage increase?',['5%','20%','125%','25%'],3,'Compare the increase of 5 with the starting value of 20.','(25 − 20) ÷ 20 × 100 = 25%. Dividing by the new value would incorrectly give 20%.')],recap:['Percent means out of 100.','Multiply the whole by the decimal to find the part.','Use the original value to calculate percentage change.'],limitations:[]},
 photosynthesis:{title:'Photosynthesis, step by step',summary:'Explore how plants use light energy to make sugars and why chloroplasts matter.',objectives:['Identify the main inputs and outputs of photosynthesis.','Explain the roles of light, chlorophyll and chloroplasts.'],sections:[
  section('Start with the big picture','In photosynthesis, plants use light energy to help convert carbon dioxide and water into sugars. Oxygen is released. The sugars store chemical energy and provide material for growth.','A growing leaf takes in carbon dioxide from the air and receives water from the roots. With light, it can make sugars.','Light supplies energy; carbon dioxide and water supply matter.'),
  section('Inside the leaf','Photosynthesis occurs in chloroplasts. Chlorophyll and other pigments absorb light. Chlorophyll absorbs red and blue light strongly and reflects or transmits more green light, helping leaves look green.','A leaf is made of cells, and many of those cells contain chloroplasts. Chloroplasts contain structures that capture light.','A chloroplast is a cell structure; chlorophyll is a pigment within it.'),
  section('Energy moves; matter is rearranged','A simplified overall model is carbon dioxide + water + light energy → sugar + oxygen. Plants also perform cellular respiration, which releases usable energy from sugars. Photosynthesis and respiration are related but different processes.','A plant can make sugars in the light and use stored sugars through respiration during both day and night.','Plants photosynthesize and also respire; they do not get all their food from soil.')],cards:[
  card('What are the main material inputs of photosynthesis?','Carbon dioxide and water.'),card('What supplies the energy for photosynthesis?','Light, often sunlight.'),card('How are chloroplast and chlorophyll different?','A chloroplast is a cell structure; chlorophyll is a light-absorbing pigment inside it.'),card('Do plants also carry out cellular respiration?','Yes. They use respiration to release usable energy from sugars.')],quiz:[
  q('Which pair supplies the main material inputs for photosynthesis?',['Oxygen and sugar','Carbon dioxide and water','Soil and oxygen','Sugar and chlorophyll'],1,'Think about what enters the simplified equation.','Carbon dioxide and water provide the matter used in photosynthesis. Light provides energy.'),
  q('Where does photosynthesis occur in plant cells?',['Nucleus','Cell wall','Chloroplasts','Vacuole'],2,'Look for the structure containing light-absorbing pigments.','Chloroplasts contain the structures and pigments involved in photosynthesis.'),
  q('Which gas is released during photosynthesis?',['Oxygen','Nitrogen','Hydrogen','Carbon dioxide'],0,'It is one of the products in the simplified model.','Oxygen is released. Carbon dioxide is a main input, rather than the gas released in this simplified model.'),
  q('Which statement is accurate?',['Plants never respire.','Plants only respire at night.','Plants get all their food from soil.','Plants photosynthesize and also respire.'],3,'Distinguish sugar production from the release of usable energy.','Plants make sugars through photosynthesis and release usable energy through cellular respiration, which occurs during day and night.')],recap:['Photosynthesis uses light energy, carbon dioxide and water.','Sugars store chemical energy; oxygen is released.','Chloroplasts contain chlorophyll.','Plants also carry out cellular respiration.'],limitations:['This is an introductory model, not a detailed account of the light reactions or carbon fixation.']},
 paragraphs:{title:'Write one clear paragraph',summary:'Turn a main idea into a focused paragraph with useful support and a clear ending.',objectives:['State a focused main idea.','Support the idea with relevant detail and explanation.'],sections:[
  section('Give the paragraph a job','Decide what one point the paragraph should communicate. A topic sentence often helps the reader see that point. Keep the scope narrow enough to explain in one paragraph.','Broad: “Exercise is good.” More focused: “A short walk at lunch can make a long workday feel more manageable.”','One paragraph should usually develop one central idea.'),
  section('Add support, then explain it','Support may be an example, observation, reason or reliable evidence. Explain how it connects to the main idea. An unsupported claim is weaker than a specific, relevant detail.','“The walk creates a break from the screen and a chance to return with a fresh perspective.” This explains how a walk might improve the experience of a workday.','Do not assume the reader will infer why your evidence matters.'),
  section('Read for focus and flow','Put ideas in a logical order. Remove details that do not serve the main point. A closing sentence can draw the details together or lead into the next paragraph. There is no universal required sentence count.','If a paragraph about lunch walks includes a long account of buying shoes, shorten or remove that detour unless it supports the point.','Revise for clarity and relevance, not an arbitrary length.')],cards:[
  card('What is a topic sentence for?','It states or signals the paragraph’s central idea.'),card('What should follow a supporting example?','An explanation of how it supports the main idea, when the connection is not already clear.'),card('How do you decide whether to remove a detail?','Ask whether it helps develop the paragraph’s central idea.'),card('Must every paragraph have exactly five sentences?','No. Length depends on purpose, audience and how much support the idea needs.')],quiz:[
  q('Which topic sentence is more focused?',['“There are many things.”','“Life is interesting.”','“A shared checklist helps a small team avoid missed handoffs.”','“Everything has advantages.”'],2,'Choose the sentence with a specific subject and a clear point.','The checklist sentence identifies a subject and a focused benefit that a paragraph can develop.'),
  q('What makes supporting detail useful?',['It is as long as possible.','It relates to and develops the main idea.','It changes the subject.','It contains difficult words.'],1,'Focus on the relationship between the detail and the main point.','Relevant detail develops the point. Length and complex vocabulary do not automatically make support stronger.'),
  q('A detail is interesting but unrelated to your main idea. What is a good revision?',['Add more unrelated details.','Repeat the topic sentence.','Keep it just because it is interesting.','Remove it or move it to a more relevant paragraph.'],3,'Think about the job of the paragraph.','Removing or relocating unrelated detail improves focus without discarding it forever.'),
  q('Which statement about paragraph length is best?',['Length depends on purpose and the support needed.','All paragraphs require five sentences.','Longer always means better.','One sentence can never form a paragraph.'],0,'Avoid an absolute rule based only on sentence count.','Purpose, audience and development guide paragraph length. There is no universal five-sentence requirement.')],recap:['Choose one central idea.','Use specific, relevant support.','Explain connections when needed.','Revise for focus and flow.'],limitations:['These are general writing strategies. Follow any specific requirements from your teacher or publication.']}
};
export function starter(id){if(!Object.hasOwn(packs,id))fail('Choose an available starter.');return validateLesson(packs[id]);}
