'use strict';
const API='https://chee-chai-chee-backend.onrender.com/api/directory';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
let page=0,rows=[],savedOnly=false,request=0,detailTicket=0,favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('korlix_directory_favorites_v1')||'[]'));}catch{}
function remember(id){if(favorites.has(id))favorites.delete(id);else if(favorites.size<50)favorites.add(id);try{localStorage.setItem('korlix_directory_favorites_v1',JSON.stringify([...favorites]));}catch{}if(savedOnly)search();else render();}
async function api(path,body){const r=await fetch(API+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;}
const photo=(b,id)=>`${API}/businesses/${encodeURIComponent(b.id)}/photos/${encodeURIComponent(id)}`;
function cover(b,cls='cover'){const d=b.details;if(d.photos?.length){const img=el('img',null,cls);img.src=photo(b,d.photos[0]);img.alt=d.name;img.loading='lazy';img.referrerPolicy='no-referrer';return img;}return el('div',d.name?.slice(0,2).toUpperCase(),cls+' placeholder');}
function verified(b){const n=el('button','✓ VERIFIED','badge');n.type='button';n.onclick=()=>alert(`KORLIX checked this owner's business email, phone and ownership evidence on ${new Date(b.verified_at).toLocaleDateString()}. The membership is active. Verification is not a guarantee of service quality.`);return n;}
function render(){const grid=$('#results');grid.replaceChildren();const list=savedOnly?rows.filter(b=>favorites.has(b.id)):rows;if(!list.length){grid.append(el('div',savedOnly?'No saved businesses on this results page. Browse businesses and tap Save.':'No businesses match yet. Try another location or category—or be the first to add yours.','empty'));return;}for(const b of list){const d=b.details,card=el('article',null,'card');card.append(cover(b));const body=el('div',null,'card-body');body.append(el('span',d.category,'category'),el('h3',d.name),el('span',[d.city,d.country].filter(Boolean).join(', ')||d.service_area,'location'),el('p',d.description.slice(0,150)+(d.description.length>150?'…':'')));if(b.verified)body.append(verified(b));const actions=el('div',null,'card-actions'),open=el('a','View business ↗'),save=el('button',favorites.has(b.id)?'♥ Saved':'♡ Save','quiet');open.href='?business='+encodeURIComponent(b.slug);open.onclick=e=>{e.preventDefault();history.pushState({},'',open.href);show(b.slug);};save.onclick=()=>remember(b.id);actions.append(open,save);body.append(actions);card.append(body);grid.append(card);}}
async function search(){const ticket=++request;$('#status').textContent='Finding businesses…';const params=new URLSearchParams({q:$('#query').value,city:$('#city').value,category:$('#category').value,offset:String(page*25),...(savedOnly?{ids:[...favorites].join(',')||'00000000-0000-0000-0000-000000000000'}:{})});try{const d=await api('/businesses?'+params);if(ticket!==request)return;rows=d.businesses;if($('#category').options.length===1)for(const c of d.categories){const o=el('option',c);o.value=c;$('#category').append(o);}render();$('#status').textContent=`${rows.length} businesses on this page`;}catch(e){if(ticket===request)$('#status').textContent=e.message;}$('#previous').disabled=page===0;$('#next').disabled=rows.length<25;}
function track(b,kind){api(`/businesses/${b.id}/metrics`,{kind}).catch(()=>{});}
function link(label,url,b){const a=el('a',label,'button small');a.href=url;if(/^https?:/.test(url)){a.target='_blank';a.rel='noopener noreferrer';}a.onclick=()=>track(b,'contact');return a;}
async function show(slug){const ticket=++detailTicket;const dialog=$('#detail'),content=$('#detail-content');content.replaceChildren(el('p','Loading business…'));if(!dialog.open)dialog.showModal();try{const b=await api('/businesses/'+encodeURIComponent(slug)),d=b.details;if(ticket!==detailTicket||!dialog.open)return;content.replaceChildren(cover(b,'detail-photo'),el('p',d.category,'eyebrow'),el('h2',d.name));document.title=d.name+' | KORLIX Business Directory';if(b.verified)content.append(verified(b));content.append(el('p',d.description,'detail-description'));const actions=el('div',null,'contact-actions');if(d.phone)actions.append(link('Call business','tel:'+d.phone.replace(/[^+\d]/g,''),b));if(d.email)actions.append(link('Email business','mailto:'+d.email,b));if(d.website)actions.append(link('Visit website ↗',d.website,b));if(d.social)actions.append(link('Social page ↗',d.social,b));if(d.address)actions.append(link('Directions ↗','https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([d.address,d.city,d.country].filter(Boolean).join(', ')),b));content.append(actions);
const info=el('div',null,'details-grid');for(const [label,value]of [['Location',[d.address,d.city,d.country].filter(Boolean).join(', ')],['Service area',d.service_area],['Business hours',d.hours],['Specialties',d.specialties],['Languages',d.languages],['Accessibility',d.accessibility],['Contact',d.public_contact_name]])if(value){const block=el('div');block.append(el('strong',label),el('p',value,'detail-description'));info.append(block);}content.append(info);
if(d.offer?.text)content.append(el('p',`${d.offer.text} · Until ${d.offer.expires}`,'notice'));
if(d.photos?.length>1){const gallery=el('div',null,'gallery');for(const id of d.photos.slice(1)){const img=el('img');img.src=photo(b,id);img.alt=d.name+' company photo';img.loading='lazy';gallery.append(img);}content.append(gallery);}
const controls=el('div',null,'contact-actions'),share=el('button','Copy listing link','quiet'),print=el('button','Print listing','quiet'),report=el('button','Report listing','quiet');share.onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+'/business-directory/?business='+encodeURIComponent(b.slug));share.textContent='Link copied';}catch{prompt('Copy this listing link',location.href);}};print.onclick=()=>window.print();report.onclick=async()=>{const reason=prompt('What should KORLIX review? Describe incorrect information, a duplicate, spam or another concern (10–1,000 characters).');if(!reason)return;try{await api(`/businesses/${b.id}/report`,{reason});alert('Report submitted for review.');}catch(e){alert(e.message);}};controls.append(share,print,report);content.append(controls,el('p','Business information is provided by its owner. Confirm details with the business before making arrangements.','location'));track(b,'view');}catch(e){content.replaceChildren(el('p',e.message));}}
$('#search').onsubmit=e=>{e.preventDefault();page=0;search();};$('#previous').onclick=()=>{page=Math.max(0,page-1);search();};$('#next').onclick=()=>{page++;search();};$('#favorites').onclick=()=>{savedOnly=!savedOnly;$('#favorites').textContent=savedOnly?'Show all businesses':'♡ Saved businesses';page=0;search();};$('#close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>{detailTicket++;history.replaceState({},'','/business-directory/');document.title='KORLIX Business Directory';});window.addEventListener('popstate',()=>{const slug=new URLSearchParams(location.search).get('business');if(slug)show(slug);else $('#detail').close();});search();const initial=new URLSearchParams(location.search);if(initial.get('business'))show(initial.get('business'));if(initial.has('membership'))$('#status').textContent='Return to KORLIX → Business Directory → My Businesses and select Refresh membership to see your payment status.';
