import {randomUUID,createHash} from 'node:crypto';
import multer from 'multer';
import {BUCKET,CREDIT_COST,AGES,STYLES,BabyBlendError,fail,uuid,options,normalizeUpload} from './ai.mjs';
const base='/api/babyblend';
const digest=b=>createHash('sha256').update(b).digest('hex');
export function registerBabyBlend(app,{database,storageDatabase=database,requireUser,aiAccess,generate,logger=console}={}){
 const active=new Set(),starting=new Set();let uploads=0;
 const call=async(user,action,id=null,data={})=>{const r=await database.rpc('korlix_babyblend_v1',{p_actor:user,p_action:action,p_id:id,p_data:data});if(r.error){const status={P0002:404,'40001':409,'54000':429,P0001:400,'42501':403}[r.error.code];if(status)fail(r.error.message,status);logger.warn('BabyBlend storage unavailable',{action,code:r.error.code});fail('BabyBlend could not save this change. Refresh before retrying.',503);}return r.data;};
 const objects=()=>storageDatabase.storage.from(BUCKET);
 const route=fn=>async(q,r)=>{r.set('Cache-Control','no-store');try{const u=await requireUser(q);if(!u?.id)fail('Sign in to use BabyBlend.',401);if(!database||!storageDatabase)fail('BabyBlend is temporarily unavailable.',503);await fn(q,r,u);}catch(e){const status=e instanceof BabyBlendError?e.status:e.statusCode===401?401:503;r.status(status).json({error:e instanceof BabyBlendError?e.message:status===401?'Sign in again to use BabyBlend.':'BabyBlend could not finish this request. Refresh before retrying.'});}};
 const publicAssets=async(rows)=>{const paths=rows.filter(a=>a.state==='ready').flatMap(a=>[a.path,a.thumb_path]);let urls=new Map();if(paths.length){const r=await objects().createSignedUrls(paths,600);if(r.error)fail('Your photos could not be loaded. Refresh shortly.',503);urls=new Map((r.data||[]).map(x=>[x.path,x.signedUrl]));}return rows.map(a=>({id:a.id,kind:a.kind,state:a.state,width:a.width,height:a.height,details:a.details,createdAt:a.created_at,imageUrl:a.state==='ready'?urls.get(a.path)||null:null,thumbnailUrl:a.state==='ready'?urls.get(a.thumb_path)||null:null}));};
 const publicJob=j=>({id:j.id,photoIds:j.photo_ids,age:j.age,style:j.style,state:j.state,result:j.result,error:j.error,charged:j.charged,createdAt:j.created_at,completedAt:j.completed_at});
 const download=async(a,thumb=false)=>{if(a.state!=='ready')fail('This photo has not finished saving.',409);const r=await objects().download(thumb?a.thumb_path:a.path);if(r.error||!r.data)fail('This photo could not be downloaded. Refresh and retry.',503);const b=Buffer.from(await r.data.arrayBuffer());if(digest(b)!==(thumb?a.thumb_digest:a.digest))fail('This photo failed its integrity check. Please upload it again.',503);return b;};
 const save=async(user,id,kind,prepared,details={})=>{const lease=randomUUID(),prefix=`${user}/${id}/`;let a=await call(user,'asset_begin',id,{kind,details,lease,path:prefix+'image.'+prepared.extension,thumb_path:prefix+'thumb.jpg',digest:digest(prepared.image),thumb_digest:digest(prepared.thumb),bytes:prepared.image.length+prepared.thumb.length,width:prepared.width,height:prepared.height});
  if(a.state==='ready')return a;for(const [path,bytes,mime]of[[a.path,prepared.image,prepared.mime],[a.thumb_path,prepared.thumb,'image/jpeg']]){const r=await objects().upload(path,bytes,{contentType:mime,upsert:true,cacheControl:'0'});if(r.error)fail('The upload was interrupted. Keep the photo selected and retry after three minutes, or remove the incomplete upload.',503);}
  if(kind==='source')a=await call(user,'asset_finish',id,{lease});return {...a,writeLease:lease};};
 const run=async(u,j)=>{active.add(j.id);try{const photos=[];for(const id of j.photo_ids){const a=await call(u.id,'asset_get',id);photos.push({...a,bytes:await download(a)});}const rendered=await generate({photos,age:j.age,style:j.style});
  const a=await save(u.id,j.id,'portrait',rendered,{age:j.age,style:j.style,photoIds:j.photo_ids});await call(u.id,'job_finish',j.id,{lease:a.writeLease,result:{assetId:a.id,summary:rendered.summary,model:rendered.model,quality:rendered.quality}});
 }catch(e){logger.warn('BabyBlend portrait failed',{errorType:e.name||'Error'});try{await call(u.id,'job_fail',j.id,{error:e instanceof BabyBlendError?e.message:'KORLIX could not finish this portrait. No credit was charged. Please retry.'});}catch{logger.warn('BabyBlend status could not be saved');}}finally{active.delete(j.id);}};
 app.get(base,route(async(_q,r,u)=>{const d=await call(u.id,'list');r.json({assets:await publicAssets(d.assets),jobs:d.jobs.map(publicJob),ages:AGES,styles:STYLES,creditCost:CREDIT_COST,limits:{sources:10,portraits:50,photoBytes:15*1024*1024,storageBytes:300*1024*1024}});}));
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024,files:1,fields:2,fieldSize:100}}).single('image');
 app.post(base+'/photos',route(async(q,r,u)=>{if(uploads>=2)fail('Photo upload is busy. Try again shortly.',429);uploads++;try{await new Promise((resolve,reject)=>upload(q,r,e=>e?reject(new BabyBlendError('Choose one JPG, PNG or WEBP photo under 15 MB.')):resolve()));const id=uuid(q.body?.request_key),prepared=await normalizeUpload(q.file),a=await save(u.id,id,'source',prepared);r.status(201).json({asset:(await publicAssets([a]))[0]});}finally{uploads--;}}));
 app.get(base+'/assets/:id/file',route(async(q,r,u)=>{const a=await call(u.id,'asset_get',uuid(q.params.id)),thumb=q.query.thumbnail==='true',bytes=await download(a,thumb),png=a.kind==='portrait'&&!thumb;r.set('Content-Type',png?'image/png':'image/jpeg');r.set('X-Content-Type-Options','nosniff');r.set('Content-Disposition',`attachment; filename="KORLIX-BabyBlend-${a.id}.${png?'png':'jpg'}"`);r.send(bytes);}));
 app.delete(base+'/assets/:id',route(async(q,r,u)=>{if(q.body?.confirmed!==true)fail('Confirm before removing this photo.');const a=await call(u.id,'asset_delete_begin',uuid(q.params.id)),removed=await objects().remove([a.path,a.thumb_path]);if(removed.error)fail('Removal is incomplete. Refresh and retry removing this photo.',503);await call(u.id,'asset_delete_finish',a.id);r.json({deleted:true});}));
 app.post(base+'/jobs',route(async(q,r,u)=>{const id=uuid(q.body?.request_key),o=options(q.body);if(q.body?.consent!==true||q.body?.adult_photo_permission!==true)fail('Confirm AI sharing and permission to use both adult photos.');
  try{const prior=await call(u.id,'job_get',id);if(prior.age!==o.age||prior.style!==o.style||JSON.stringify(prior.photo_ids)!==JSON.stringify(o.photo_ids))fail('Use a new request after changing photos or options.',409);return r.json({job:publicJob(prior)});}catch(e){if(e.status!==404)throw e;}
  if(active.size+starting.size>=2)fail('KORLIX is finishing other portraits. Try again shortly.',429);if(starting.has(id))fail('Your portrait is starting. Refresh BabyBlend.',409);starting.add(id);
  try{const access=await aiAccess(u);if(!access?.allowed)fail(access?.reason||'BabyBlend creation requires Ultra Premium or Enterprise.',access?.status||403);const j=await call(u.id,'job_begin',id,{...o,usage_id:access.usageId});r.status(202).json({job:publicJob(j)});if(!j.replayed&&!active.has(j.id))void run(u,j);}finally{starting.delete(id);}
 }));
 app.get(base+'/jobs/:id',route(async(q,r,u)=>{const j=await call(u.id,'job_get',uuid(q.params.id));let asset=null;if(j.state==='completed'&&j.result?.assetId){try{asset=(await publicAssets([await call(u.id,'asset_get',j.result.assetId)]))[0];}catch(e){if(e.status!==404)throw e;}}r.json({job:publicJob(j),asset});}));
 return {active};
}
